/**
 * FFOR: Fast-Forward Offline Receive — wire codecs (spec §7, §11.1, §14).
 *
 * All messages use odd types in the custom range (55001–55023) so they are
 * ignorable by non-implementing peers. All multi-byte integers are big-endian.
 * Every message body begins `[32: channel_id][32: epoch_id]`.
 *
 * Signed messages (ff_init, ff_accept — spec §7 "✍"): the `signature` field is
 * the FINAL 64 bytes of the message body. The node-key signature is computed
 * over the SHA256 of:
 *
 *     [2: message type (big-endian)] || [body bytes excluding the final 64]
 *
 * i.e. the digest covers the type plus every body byte that precedes the
 * signature (including the TLV stream, which sits between the fixed fields and
 * the signature). These signatures exist for non-repudiation (fraud proofs,
 * spec §12.2), since Noise transport authenticates but does not produce
 * third-party-verifiable evidence.
 */

import crypto from 'crypto';
import { sign, verify } from '../crypto/ecdh';
import {
	encodeTlvStream,
	decodeTlvStream,
	findTlvRecord,
	ITlvRecord
} from '../message/tlv';

// ---- Message type ids (spec §14, provisional pending bLIP assignment) ----

export const FF_INIT_TYPE = 55001;
export const FF_ACCEPT_TYPE = 55003;
export const FF_INVOICES_TYPE = 55005;
export const FF_ESCAPE_SIGS_TYPE = 55009;
export const FF_BEGIN_TYPE = 55011;
export const FF_END_TYPE = 55021;
export const FF_ERROR_TYPE = 55023;

/** [32: channel_id][32: epoch_id] prefix common to every FFOR message. */
const FF_HEADER_LEN = 64;
const SIG_LEN = 64;

// ---- Interfaces ----

export interface IFforHeader {
	channelId: Buffer;
	epochId: Buffer;
}

/** ff_init (55001, R→S) ✍ — spec §7.1. */
export interface IFforInitMessage extends IFforHeader {
	variant: number;
	budgetMsat: bigint;
	maxPayments: number;
	minPaymentMsat: bigint;
	settlementDeadline: number;
	voucherExpiry: number;
	feeBaseMsat: number;
	feeProportionalMillionths: number;
	escapeGranularityMsat: bigint;
	rPerCommitmentPoints: Buffer[];
	/** TLV 1 — Variant B only: hashes generated by R's tower (K×32). */
	paymentHashes?: Buffer[];
	/** TLV 3 — Variant B only. */
	towerNodeId?: Buffer;
	/** TLV 5 — Variant B only. */
	towerUri?: string;
	/** R's node-key signature (final 64 bytes of the body). */
	signature: Buffer;
}

/** ff_accept (55003, S→R) ✍ — spec §7.2. */
export interface IFforAcceptMessage extends IFforHeader {
	/** `n0`: S's commitment number at epoch start (explicit, anchors evidence). */
	sCommitmentNumber: bigint;
	/** TLV 1 — Variant A only: S-generated hashes (K×32). */
	paymentHashes?: Buffer[];
	/**
	 * TLV 7 (odd, PROTOTYPE EXTENSION — spec erratum): S's offered-HTLC counter
	 * at epoch start. Voucher seq k maps to HTLC id s_htlc_id_base + (k−1) at
	 * reconciliation; the spec assigns no voucher HTLC ids and R cannot observe
	 * S's counter, so it must be communicated.
	 */
	sHtlcIdBase?: bigint;
	/** S's node-key signature (final 64 bytes of the body). */
	signature: Buffer;
}

/** ff_invoices (55005, R→S) — spec §7.3. */
export interface IFforInvoicesMessage extends IFforHeader {
	/** Length-prefixed BOLT 11 strings; count MUST equal K. */
	invoices: string[];
}

/** ff_escape_sigs (55009, R→S) — spec §7.4, optional iff G > 0. */
export interface IFforEscapeSigsMessage extends IFforHeader {
	/** R's signatures on escape commitments E_1…E_J, J = ceil(budget/G). */
	escapeSigs: Buffer[];
	/**
	 * R's signatures for the aggregate voucher spend path on each E_j —
	 * "not required in v1 (bare-sig voucher, §10), reserved". Encoded only when
	 * provided; tolerated as absent on decode.
	 */
	escapeHtlcSigs?: Buffer[];
}

/** ff_begin (55011, R→S) — spec §7.5. */
export interface IFforBeginMessage extends IFforHeader {
	/** For audit; MUST be within a few blocks of the current tip. */
	epochStartHeight: number;
}

/** ff_end (55021, both directions) — spec §11.1 step 5. Header only. */
export type IFforEndMessage = IFforHeader;

/** ff_error (55023, both directions) — spec §11.1. */
export interface IFforErrorMessage extends IFforHeader {
	/** Free-form diagnostic, `[2: len][len: data]` (BOLT 1 error style). */
	data: Buffer;
}

// ---- Signature helpers ----

/**
 * Digest a signed FFOR message: SHA256 over the 2-byte big-endian message type
 * followed by every body byte preceding the final-64-byte signature field.
 */
export function fforMessageDigest(type: number, payload: Buffer): Buffer {
	if (payload.length < FF_HEADER_LEN + SIG_LEN) {
		throw new Error('FFOR signed message too short to digest');
	}
	const typeBuf = Buffer.alloc(2);
	typeBuf.writeUInt16BE(type, 0);
	return crypto
		.createHash('sha256')
		.update(typeBuf)
		.update(payload.subarray(0, payload.length - SIG_LEN))
		.digest();
}

/**
 * Sign an encoded FFOR message body in place: computes the digest (which by
 * construction excludes the final 64 bytes) and writes the node-key signature
 * into those final 64 bytes. Returns the same buffer for chaining.
 */
export function signFforMessage(
	type: number,
	payload: Buffer,
	nodePrivateKey: Buffer
): Buffer {
	const sig = sign(fforMessageDigest(type, payload), nodePrivateKey);
	sig.copy(payload, payload.length - SIG_LEN);
	return payload;
}

/** Verify the node-key signature carried in an encoded FFOR message body. */
export function verifyFforMessageSignature(
	type: number,
	payload: Buffer,
	nodeId: Buffer
): boolean {
	if (payload.length < FF_HEADER_LEN + SIG_LEN) return false;
	try {
		return verify(
			fforMessageDigest(type, payload),
			nodeId,
			payload.subarray(payload.length - SIG_LEN)
		);
	} catch {
		return false;
	}
}

// ---- Common helpers ----

function writeHeader(buf: Buffer, msg: IFforHeader): number {
	if (msg.channelId.length !== 32) {
		throw new Error(`channel_id must be 32 bytes, got ${msg.channelId.length}`);
	}
	if (msg.epochId.length !== 32) {
		throw new Error(`epoch_id must be 32 bytes, got ${msg.epochId.length}`);
	}
	msg.channelId.copy(buf, 0);
	msg.epochId.copy(buf, 32);
	return FF_HEADER_LEN;
}

function readHeader(
	payload: Buffer,
	name: string
): { channelId: Buffer; epochId: Buffer } {
	if (payload.length < FF_HEADER_LEN) {
		throw new Error(
			`${name} too short: need at least ${FF_HEADER_LEN} bytes, got ${payload.length}`
		);
	}
	return {
		channelId: Buffer.from(payload.subarray(0, 32)),
		epochId: Buffer.from(payload.subarray(32, 64))
	};
}

/**
 * Decode just the `[channel_id][epoch_id]` prefix — used by the manager to
 * route an FFOR message to its channel before full decoding.
 */
export function decodeFforHeader(payload: Buffer): IFforHeader {
	return readHeader(payload, 'FFOR message');
}

/** Split a concatenated K×32 hash blob into 32-byte Buffers. */
function splitHashes(value: Buffer, tlvName: string): Buffer[] {
	if (value.length === 0 || value.length % 32 !== 0) {
		throw new Error(
			`${tlvName}: length must be a positive multiple of 32, got ${value.length}`
		);
	}
	const hashes: Buffer[] = [];
	for (let i = 0; i < value.length; i += 32) {
		hashes.push(Buffer.from(value.subarray(i, i + 32)));
	}
	return hashes;
}

// ---- ff_init (55001) ----

const FF_INIT_TLV_PAYMENT_HASHES = 1n;
const FF_INIT_TLV_TOWER_NODE_ID = 3n;
const FF_INIT_TLV_TOWER_URI = 5n;
const FF_INIT_KNOWN_TLVS = new Set<bigint>([
	FF_INIT_TLV_PAYMENT_HASHES,
	FF_INIT_TLV_TOWER_NODE_ID,
	FF_INIT_TLV_TOWER_URI
]);

/**
 * Encode ff_init. `msg.signature` may be a 64-byte placeholder (e.g. zeros)
 * that the caller overwrites via signFforMessage().
 */
export function encodeFforInitMessage(msg: IFforInitMessage): Buffer {
	if (msg.signature.length !== SIG_LEN) {
		throw new Error(`signature must be 64 bytes, got ${msg.signature.length}`);
	}
	for (const p of msg.rPerCommitmentPoints) {
		if (p.length !== 33) {
			throw new Error(`per-commitment point must be 33 bytes, got ${p.length}`);
		}
	}
	if (msg.rPerCommitmentPoints.length > 0xffff) {
		throw new Error('too many per-commitment points');
	}

	// Fixed fields after the header: 1+8+2+8+4+4+4+4+8 = 43 bytes, then
	// [2: num_points][num_points × 33].
	const fixed = Buffer.alloc(
		FF_HEADER_LEN + 43 + 2 + msg.rPerCommitmentPoints.length * 33
	);
	let o = writeHeader(fixed, msg);
	fixed.writeUInt8(msg.variant, o);
	o += 1;
	fixed.writeBigUInt64BE(msg.budgetMsat, o);
	o += 8;
	fixed.writeUInt16BE(msg.maxPayments, o);
	o += 2;
	fixed.writeBigUInt64BE(msg.minPaymentMsat, o);
	o += 8;
	fixed.writeUInt32BE(msg.settlementDeadline, o);
	o += 4;
	fixed.writeUInt32BE(msg.voucherExpiry, o);
	o += 4;
	fixed.writeUInt32BE(msg.feeBaseMsat, o);
	o += 4;
	fixed.writeUInt32BE(msg.feeProportionalMillionths, o);
	o += 4;
	fixed.writeBigUInt64BE(msg.escapeGranularityMsat, o);
	o += 8;
	fixed.writeUInt16BE(msg.rPerCommitmentPoints.length, o);
	o += 2;
	for (const p of msg.rPerCommitmentPoints) {
		p.copy(fixed, o);
		o += 33;
	}

	const records: ITlvRecord[] = [];
	if (msg.paymentHashes && msg.paymentHashes.length > 0) {
		records.push({
			type: FF_INIT_TLV_PAYMENT_HASHES,
			value: Buffer.concat(msg.paymentHashes)
		});
	}
	if (msg.towerNodeId) {
		if (msg.towerNodeId.length !== 33) {
			throw new Error(
				`tower_node_id must be 33 bytes, got ${msg.towerNodeId.length}`
			);
		}
		records.push({ type: FF_INIT_TLV_TOWER_NODE_ID, value: msg.towerNodeId });
	}
	if (msg.towerUri !== undefined) {
		records.push({
			type: FF_INIT_TLV_TOWER_URI,
			value: Buffer.from(msg.towerUri, 'utf8')
		});
	}

	return Buffer.concat([fixed, encodeTlvStream(records), msg.signature]);
}

export function decodeFforInitMessage(payload: Buffer): IFforInitMessage {
	const header = readHeader(payload, 'ff_init');
	// header(64) + fixed(43) + num_points(2) + signature(64)
	if (payload.length < FF_HEADER_LEN + 43 + 2 + SIG_LEN) {
		throw new Error(`ff_init too short: got ${payload.length}`);
	}
	let o = FF_HEADER_LEN;
	const variant = payload.readUInt8(o);
	o += 1;
	const budgetMsat = payload.readBigUInt64BE(o);
	o += 8;
	const maxPayments = payload.readUInt16BE(o);
	o += 2;
	const minPaymentMsat = payload.readBigUInt64BE(o);
	o += 8;
	const settlementDeadline = payload.readUInt32BE(o);
	o += 4;
	const voucherExpiry = payload.readUInt32BE(o);
	o += 4;
	const feeBaseMsat = payload.readUInt32BE(o);
	o += 4;
	const feeProportionalMillionths = payload.readUInt32BE(o);
	o += 4;
	const escapeGranularityMsat = payload.readBigUInt64BE(o);
	o += 8;
	const numPoints = payload.readUInt16BE(o);
	o += 2;
	if (payload.length < o + numPoints * 33 + SIG_LEN) {
		throw new Error('ff_init truncated in r_per_commitment_points');
	}
	const rPerCommitmentPoints: Buffer[] = [];
	for (let i = 0; i < numPoints; i++) {
		rPerCommitmentPoints.push(Buffer.from(payload.subarray(o, o + 33)));
		o += 33;
	}

	// Everything between the points and the final-64-byte signature is TLV.
	const tlvEnd = payload.length - SIG_LEN;
	const { records } = decodeTlvStream(
		payload.subarray(o, tlvEnd),
		0,
		FF_INIT_KNOWN_TLVS
	);
	const hashBlob = findTlvRecord(records, FF_INIT_TLV_PAYMENT_HASHES);
	const towerNodeId = findTlvRecord(records, FF_INIT_TLV_TOWER_NODE_ID);
	if (towerNodeId && towerNodeId.length !== 33) {
		throw new Error(
			`ff_init tower_node_id must be 33 bytes, got ${towerNodeId.length}`
		);
	}
	const towerUriBuf = findTlvRecord(records, FF_INIT_TLV_TOWER_URI);

	return {
		channelId: header.channelId,
		epochId: header.epochId,
		variant,
		budgetMsat,
		maxPayments,
		minPaymentMsat,
		settlementDeadline,
		voucherExpiry,
		feeBaseMsat,
		feeProportionalMillionths,
		escapeGranularityMsat,
		rPerCommitmentPoints,
		paymentHashes: hashBlob
			? splitHashes(hashBlob, 'ff_init payment_hashes')
			: undefined,
		towerNodeId: towerNodeId ? Buffer.from(towerNodeId) : undefined,
		towerUri: towerUriBuf ? towerUriBuf.toString('utf8') : undefined,
		signature: Buffer.from(payload.subarray(tlvEnd))
	};
}

// ---- ff_accept (55003) ----

const FF_ACCEPT_TLV_PAYMENT_HASHES = 1n;
const FF_ACCEPT_TLV_S_HTLC_ID_BASE = 7n;
const FF_ACCEPT_KNOWN_TLVS = new Set<bigint>([
	FF_ACCEPT_TLV_PAYMENT_HASHES,
	FF_ACCEPT_TLV_S_HTLC_ID_BASE
]);

export function encodeFforAcceptMessage(msg: IFforAcceptMessage): Buffer {
	if (msg.signature.length !== SIG_LEN) {
		throw new Error(`signature must be 64 bytes, got ${msg.signature.length}`);
	}
	const fixed = Buffer.alloc(FF_HEADER_LEN + 8);
	const o = writeHeader(fixed, msg);
	fixed.writeBigUInt64BE(msg.sCommitmentNumber, o);

	const records: ITlvRecord[] = [];
	if (msg.paymentHashes && msg.paymentHashes.length > 0) {
		records.push({
			type: FF_ACCEPT_TLV_PAYMENT_HASHES,
			value: Buffer.concat(msg.paymentHashes)
		});
	}
	if (msg.sHtlcIdBase !== undefined) {
		const v = Buffer.alloc(8);
		v.writeBigUInt64BE(msg.sHtlcIdBase, 0);
		records.push({ type: FF_ACCEPT_TLV_S_HTLC_ID_BASE, value: v });
	}

	return Buffer.concat([fixed, encodeTlvStream(records), msg.signature]);
}

export function decodeFforAcceptMessage(payload: Buffer): IFforAcceptMessage {
	const header = readHeader(payload, 'ff_accept');
	if (payload.length < FF_HEADER_LEN + 8 + SIG_LEN) {
		throw new Error(`ff_accept too short: got ${payload.length}`);
	}
	const sCommitmentNumber = payload.readBigUInt64BE(FF_HEADER_LEN);
	const tlvEnd = payload.length - SIG_LEN;
	const { records } = decodeTlvStream(
		payload.subarray(FF_HEADER_LEN + 8, tlvEnd),
		0,
		FF_ACCEPT_KNOWN_TLVS
	);
	const hashBlob = findTlvRecord(records, FF_ACCEPT_TLV_PAYMENT_HASHES);
	const idBase = findTlvRecord(records, FF_ACCEPT_TLV_S_HTLC_ID_BASE);
	if (idBase && idBase.length !== 8) {
		throw new Error(
			`ff_accept s_htlc_id_base must be 8 bytes, got ${idBase.length}`
		);
	}

	return {
		channelId: header.channelId,
		epochId: header.epochId,
		sCommitmentNumber,
		paymentHashes: hashBlob
			? splitHashes(hashBlob, 'ff_accept payment_hashes')
			: undefined,
		sHtlcIdBase: idBase ? idBase.readBigUInt64BE(0) : undefined,
		signature: Buffer.from(payload.subarray(tlvEnd))
	};
}

// ---- ff_invoices (55005) ----

export function encodeFforInvoicesMessage(msg: IFforInvoicesMessage): Buffer {
	if (msg.invoices.length > 0xffff) {
		throw new Error('too many invoices');
	}
	const parts: Buffer[] = [];
	const fixed = Buffer.alloc(FF_HEADER_LEN + 2);
	const o = writeHeader(fixed, msg);
	fixed.writeUInt16BE(msg.invoices.length, o);
	parts.push(fixed);
	for (const inv of msg.invoices) {
		const b = Buffer.from(inv, 'utf8');
		if (b.length > 0xffff) {
			throw new Error('invoice string too long');
		}
		const len = Buffer.alloc(2);
		len.writeUInt16BE(b.length, 0);
		parts.push(len, b);
	}
	return Buffer.concat(parts);
}

export function decodeFforInvoicesMessage(
	payload: Buffer
): IFforInvoicesMessage {
	const header = readHeader(payload, 'ff_invoices');
	if (payload.length < FF_HEADER_LEN + 2) {
		throw new Error(`ff_invoices too short: got ${payload.length}`);
	}
	let o = FF_HEADER_LEN;
	const num = payload.readUInt16BE(o);
	o += 2;
	const invoices: string[] = [];
	for (let i = 0; i < num; i++) {
		if (o + 2 > payload.length) {
			throw new Error('ff_invoices truncated in invoice length');
		}
		const len = payload.readUInt16BE(o);
		o += 2;
		if (o + len > payload.length) {
			throw new Error('ff_invoices truncated in invoice body');
		}
		invoices.push(payload.subarray(o, o + len).toString('utf8'));
		o += len;
	}
	return { channelId: header.channelId, epochId: header.epochId, invoices };
}

// ---- ff_escape_sigs (55009) ----

export function encodeFforEscapeSigsMessage(
	msg: IFforEscapeSigsMessage
): Buffer {
	const j = msg.escapeSigs.length;
	if (j > 0xffff) {
		throw new Error('too many escape sigs');
	}
	for (const s of msg.escapeSigs) {
		if (s.length !== SIG_LEN) {
			throw new Error(`escape sig must be 64 bytes, got ${s.length}`);
		}
	}
	if (msg.escapeHtlcSigs) {
		if (msg.escapeHtlcSigs.length !== j) {
			throw new Error(
				`escape_htlc_sigs count ${msg.escapeHtlcSigs.length} != num_escapes ${j}`
			);
		}
		for (const s of msg.escapeHtlcSigs) {
			if (s.length !== SIG_LEN) {
				throw new Error(`escape HTLC sig must be 64 bytes, got ${s.length}`);
			}
		}
	}

	const fixed = Buffer.alloc(FF_HEADER_LEN + 2);
	const o = writeHeader(fixed, msg);
	fixed.writeUInt16BE(j, o);
	return Buffer.concat([
		fixed,
		...msg.escapeSigs,
		...(msg.escapeHtlcSigs ?? [])
	]);
}

export function decodeFforEscapeSigsMessage(
	payload: Buffer
): IFforEscapeSigsMessage {
	const header = readHeader(payload, 'ff_escape_sigs');
	if (payload.length < FF_HEADER_LEN + 2) {
		throw new Error(`ff_escape_sigs too short: got ${payload.length}`);
	}
	let o = FF_HEADER_LEN;
	const j = payload.readUInt16BE(o);
	o += 2;
	if (payload.length < o + j * SIG_LEN) {
		throw new Error('ff_escape_sigs truncated in escape_sigs');
	}
	const escapeSigs: Buffer[] = [];
	for (let i = 0; i < j; i++) {
		escapeSigs.push(Buffer.from(payload.subarray(o, o + SIG_LEN)));
		o += SIG_LEN;
	}
	// escape_htlc_sigs are reserved in v1 — tolerate their absence.
	let escapeHtlcSigs: Buffer[] | undefined;
	if (payload.length >= o + j * SIG_LEN && j > 0) {
		escapeHtlcSigs = [];
		for (let i = 0; i < j; i++) {
			escapeHtlcSigs.push(Buffer.from(payload.subarray(o, o + SIG_LEN)));
			o += SIG_LEN;
		}
	}
	return {
		channelId: header.channelId,
		epochId: header.epochId,
		escapeSigs,
		escapeHtlcSigs
	};
}

// ---- ff_begin (55011) ----

export function encodeFforBeginMessage(msg: IFforBeginMessage): Buffer {
	const buf = Buffer.alloc(FF_HEADER_LEN + 4);
	const o = writeHeader(buf, msg);
	buf.writeUInt32BE(msg.epochStartHeight, o);
	return buf;
}

export function decodeFforBeginMessage(payload: Buffer): IFforBeginMessage {
	const header = readHeader(payload, 'ff_begin');
	if (payload.length < FF_HEADER_LEN + 4) {
		throw new Error(`ff_begin too short: got ${payload.length}`);
	}
	return {
		channelId: header.channelId,
		epochId: header.epochId,
		epochStartHeight: payload.readUInt32BE(FF_HEADER_LEN)
	};
}

// ---- ff_end (55021) ----

export function encodeFforEndMessage(msg: IFforEndMessage): Buffer {
	const buf = Buffer.alloc(FF_HEADER_LEN);
	writeHeader(buf, msg);
	return buf;
}

export function decodeFforEndMessage(payload: Buffer): IFforEndMessage {
	return readHeader(payload, 'ff_end');
}

// ---- ff_error (55023) ----

export function encodeFforErrorMessage(msg: IFforErrorMessage): Buffer {
	if (msg.data.length > 0xffff) {
		throw new Error('ff_error data too long');
	}
	const buf = Buffer.alloc(FF_HEADER_LEN + 2 + msg.data.length);
	let o = writeHeader(buf, msg);
	buf.writeUInt16BE(msg.data.length, o);
	o += 2;
	msg.data.copy(buf, o);
	return buf;
}

export function decodeFforErrorMessage(payload: Buffer): IFforErrorMessage {
	const header = readHeader(payload, 'ff_error');
	if (payload.length < FF_HEADER_LEN + 2) {
		throw new Error(`ff_error too short: got ${payload.length}`);
	}
	const len = payload.readUInt16BE(FF_HEADER_LEN);
	if (payload.length < FF_HEADER_LEN + 2 + len) {
		throw new Error('ff_error truncated in data');
	}
	return {
		channelId: header.channelId,
		epochId: header.epochId,
		data: Buffer.from(
			payload.subarray(FF_HEADER_LEN + 2, FF_HEADER_LEN + 2 + len)
		)
	};
}

// ═════════════════════ M2: settlement + reconciliation ═════════════════════

export const FF_SETTLEMENT_TYPE = 55013;
export const FF_RECONCILE_TYPE = 55015;
export const FF_RECONCILE_ACK_TYPE = 55017;
export const FF_REVOKE_BATCH_TYPE = 55019;

// ---- ff_settlement (55013, S→R and S→T) ✍ — spec §9.1 ----

const FF_SETTLEMENT_TLV_REVOCATION_SECRET_N0 = 1n;
const FF_SETTLEMENT_TLV_PREIMAGE = 3n;
const FF_SETTLEMENT_TLV_UPSTREAM_SCID = 5n;
const FF_SETTLEMENT_KNOWN_TLVS = new Set<bigint>([
	FF_SETTLEMENT_TLV_REVOCATION_SECRET_N0,
	FF_SETTLEMENT_TLV_PREIMAGE,
	FF_SETTLEMENT_TLV_UPSTREAM_SCID
]);

/** The settlement package (spec §9.1). All sigs are BOLT 2 compact 64-byte. */
export interface IFforSettlementMessage extends IFforHeader {
	/** 1-based, strictly sequential. */
	seq: number;
	/** MUST equal H_seq. */
	paymentHash: Buffer;
	/** As received upstream. */
	htlcAmountMsat: bigint;
	/** v_i; MUST equal htlc_amount − fee(htlc_amount). */
	voucherAmountMsat: bigint;
	/** n_R + seq. */
	rCommitmentNumber: bigint;
	/** S's signature on C_i^R (BOLT 2 compact encoding). */
	commitmentSig: Buffer;
	/**
	 * S's HTLC-success signatures for EVERY voucher output on C_i^R, in BOLT 3
	 * commitment OUTPUT-INDEX order — not voucher seq order (§8) —
	 * (SIGHASH_SINGLE|ANYONECANPAY, anchor rules). Count = seq.
	 */
	htlcSigs: Buffer[];
	/** TLV 1 — REQUIRED in seq 1, both variants: per_commitment_secret_S[n0]. */
	revocationSecretN0?: Buffer;
	/** TLV 3 — Variant A only: P_i. */
	preimage?: Buffer;
	/** TLV 5 — optional, audit. */
	upstreamScid?: Buffer;
	/** S's node-key sig over the package (final 64 bytes; fraud-proof anchor). */
	signature: Buffer;
}

export function encodeFforSettlementMessage(
	msg: IFforSettlementMessage
): Buffer {
	if (msg.signature.length !== SIG_LEN) {
		throw new Error(`signature must be 64 bytes, got ${msg.signature.length}`);
	}
	if (msg.commitmentSig.length !== SIG_LEN) {
		throw new Error(
			`commitment_sig must be 64 bytes, got ${msg.commitmentSig.length}`
		);
	}
	if (msg.htlcSigs.length !== msg.seq) {
		throw new Error(
			`num_htlc_sigs ${msg.htlcSigs.length} != seq ${msg.seq} (§9.1: every voucher is re-signed)`
		);
	}
	for (const s of msg.htlcSigs) {
		if (s.length !== SIG_LEN) {
			throw new Error(`htlc_sig must be 64 bytes, got ${s.length}`);
		}
	}
	if (msg.paymentHash.length !== 32) {
		throw new Error('payment_hash must be 32 bytes');
	}

	// [2 seq][32 hash][8 htlc_amount][8 voucher_amount][8 r_commitment_number]
	// [64 commitment_sig][2 num_htlc_sigs][seq×64 htlc_sigs][TLV][64 signature]
	const fixed = Buffer.alloc(FF_HEADER_LEN + 2 + 32 + 8 + 8 + 8 + 64 + 2);
	let o = writeHeader(fixed, msg);
	fixed.writeUInt16BE(msg.seq, o);
	o += 2;
	msg.paymentHash.copy(fixed, o);
	o += 32;
	fixed.writeBigUInt64BE(msg.htlcAmountMsat, o);
	o += 8;
	fixed.writeBigUInt64BE(msg.voucherAmountMsat, o);
	o += 8;
	fixed.writeBigUInt64BE(msg.rCommitmentNumber, o);
	o += 8;
	msg.commitmentSig.copy(fixed, o);
	o += 64;
	fixed.writeUInt16BE(msg.htlcSigs.length, o);

	const records: ITlvRecord[] = [];
	if (msg.revocationSecretN0) {
		if (msg.revocationSecretN0.length !== 32) {
			throw new Error('revocation_secret_n0 must be 32 bytes');
		}
		records.push({
			type: FF_SETTLEMENT_TLV_REVOCATION_SECRET_N0,
			value: msg.revocationSecretN0
		});
	}
	if (msg.preimage) {
		if (msg.preimage.length !== 32) {
			throw new Error('preimage must be 32 bytes');
		}
		records.push({ type: FF_SETTLEMENT_TLV_PREIMAGE, value: msg.preimage });
	}
	if (msg.upstreamScid) {
		if (msg.upstreamScid.length !== 8) {
			throw new Error('upstream_scid must be 8 bytes');
		}
		records.push({
			type: FF_SETTLEMENT_TLV_UPSTREAM_SCID,
			value: msg.upstreamScid
		});
	}

	return Buffer.concat([
		fixed,
		...msg.htlcSigs,
		encodeTlvStream(records),
		msg.signature
	]);
}

export function decodeFforSettlementMessage(
	payload: Buffer
): IFforSettlementMessage {
	const header = readHeader(payload, 'ff_settlement');
	const FIXED = FF_HEADER_LEN + 2 + 32 + 8 + 8 + 8 + 64 + 2;
	if (payload.length < FIXED + SIG_LEN) {
		throw new Error(`ff_settlement too short: got ${payload.length}`);
	}
	let o = FF_HEADER_LEN;
	const seq = payload.readUInt16BE(o);
	o += 2;
	const paymentHash = Buffer.from(payload.subarray(o, o + 32));
	o += 32;
	const htlcAmountMsat = payload.readBigUInt64BE(o);
	o += 8;
	const voucherAmountMsat = payload.readBigUInt64BE(o);
	o += 8;
	const rCommitmentNumber = payload.readBigUInt64BE(o);
	o += 8;
	const commitmentSig = Buffer.from(payload.subarray(o, o + 64));
	o += 64;
	const numHtlcSigs = payload.readUInt16BE(o);
	o += 2;
	if (payload.length < o + numHtlcSigs * SIG_LEN + SIG_LEN) {
		throw new Error('ff_settlement truncated in htlc_sigs');
	}
	const htlcSigs: Buffer[] = [];
	for (let i = 0; i < numHtlcSigs; i++) {
		htlcSigs.push(Buffer.from(payload.subarray(o, o + SIG_LEN)));
		o += SIG_LEN;
	}
	const tlvEnd = payload.length - SIG_LEN;
	const { records } = decodeTlvStream(
		payload.subarray(o, tlvEnd),
		0,
		FF_SETTLEMENT_KNOWN_TLVS
	);
	const secret = findTlvRecord(records, FF_SETTLEMENT_TLV_REVOCATION_SECRET_N0);
	if (secret && secret.length !== 32) {
		throw new Error('ff_settlement revocation_secret_n0 must be 32 bytes');
	}
	const preimage = findTlvRecord(records, FF_SETTLEMENT_TLV_PREIMAGE);
	if (preimage && preimage.length !== 32) {
		throw new Error('ff_settlement preimage must be 32 bytes');
	}
	const scid = findTlvRecord(records, FF_SETTLEMENT_TLV_UPSTREAM_SCID);
	if (scid && scid.length !== 8) {
		throw new Error('ff_settlement upstream_scid must be 8 bytes');
	}

	return {
		channelId: header.channelId,
		epochId: header.epochId,
		seq,
		paymentHash,
		htlcAmountMsat,
		voucherAmountMsat,
		rCommitmentNumber,
		commitmentSig,
		htlcSigs,
		revocationSecretN0: secret ? Buffer.from(secret) : undefined,
		preimage: preimage ? Buffer.from(preimage) : undefined,
		upstreamScid: scid ? Buffer.from(scid) : undefined,
		signature: Buffer.from(payload.subarray(tlvEnd))
	};
}

// ---- ff_reconcile (55015, R→S) — spec §11.1 step 2 ----

/**
 * R signs S's catch-up commitment C^S_new at n0+2 (n0+1 when G = 0),
 * mirroring C_j^R exactly (same j vouchers, now S-offered HTLCs).
 */
export interface IFforReconcileMessage extends IFforHeader {
	newCommitmentNumber: bigint;
	/** R's signature on C^S_new (BOLT 2 compact). */
	commitmentSig: Buffer;
	/** R's second-level sigs for every voucher on C^S_new, output-index order. */
	htlcSigs: Buffer[];
	/** R's per-commitment point for n_R + j + 1. */
	rNextPerCommitmentPoint: Buffer;
}

export function encodeFforReconcileMessage(msg: IFforReconcileMessage): Buffer {
	if (msg.commitmentSig.length !== SIG_LEN) {
		throw new Error('commitment_sig must be 64 bytes');
	}
	if (msg.rNextPerCommitmentPoint.length !== 33) {
		throw new Error('r_next_per_commitment_point must be 33 bytes');
	}
	for (const s of msg.htlcSigs) {
		if (s.length !== SIG_LEN) {
			throw new Error('htlc_sig must be 64 bytes');
		}
	}
	const fixed = Buffer.alloc(FF_HEADER_LEN + 8 + 64 + 2);
	let o = writeHeader(fixed, msg);
	fixed.writeBigUInt64BE(msg.newCommitmentNumber, o);
	o += 8;
	msg.commitmentSig.copy(fixed, o);
	o += 64;
	fixed.writeUInt16BE(msg.htlcSigs.length, o);
	return Buffer.concat([fixed, ...msg.htlcSigs, msg.rNextPerCommitmentPoint]);
}

export function decodeFforReconcileMessage(
	payload: Buffer
): IFforReconcileMessage {
	const header = readHeader(payload, 'ff_reconcile');
	const FIXED = FF_HEADER_LEN + 8 + 64 + 2;
	if (payload.length < FIXED + 33) {
		throw new Error(`ff_reconcile too short: got ${payload.length}`);
	}
	let o = FF_HEADER_LEN;
	const newCommitmentNumber = payload.readBigUInt64BE(o);
	o += 8;
	const commitmentSig = Buffer.from(payload.subarray(o, o + 64));
	o += 64;
	const num = payload.readUInt16BE(o);
	o += 2;
	if (payload.length < o + num * SIG_LEN + 33) {
		throw new Error('ff_reconcile truncated in htlc_sigs');
	}
	const htlcSigs: Buffer[] = [];
	for (let i = 0; i < num; i++) {
		htlcSigs.push(Buffer.from(payload.subarray(o, o + SIG_LEN)));
		o += SIG_LEN;
	}
	return {
		channelId: header.channelId,
		epochId: header.epochId,
		newCommitmentNumber,
		commitmentSig,
		htlcSigs,
		rNextPerCommitmentPoint: Buffer.from(payload.subarray(o, o + 33))
	};
}

// ---- ff_reconcile_ack (55017, S→R) — spec §11.1 step 3 ----

const FF_RECONCILE_ACK_TLV_SECRET_N0 = 1n;
const FF_RECONCILE_ACK_TLV_SECRET_N0_PLUS_1 = 3n;
const FF_RECONCILE_ACK_KNOWN_TLVS = new Set<bigint>([
	FF_RECONCILE_ACK_TLV_SECRET_N0,
	FF_RECONCILE_ACK_TLV_SECRET_N0_PLUS_1
]);

/**
 * Body layout: the fixed field precedes the TLV stream (standard LN layout;
 * the spec's §11.1 prose lists the TLVs first — spec erratum, layout chosen
 * here is normative for the prototype).
 */
export interface IFforReconcileAckMessage extends IFforHeader {
	/** S's per-commitment point for new_commitment_number + 1. */
	sNextPerCommitmentPoint: Buffer;
	/** TLV 1 — iff j == 0 (otherwise it went out in package 1). */
	revocationSecretN0?: Buffer;
	/** TLV 3 — iff escapes were signed: per_commitment_secret_S[n0+1]. */
	revocationSecretN0Plus1?: Buffer;
}

export function encodeFforReconcileAckMessage(
	msg: IFforReconcileAckMessage
): Buffer {
	if (msg.sNextPerCommitmentPoint.length !== 33) {
		throw new Error('s_next_per_commitment_point must be 33 bytes');
	}
	const fixed = Buffer.alloc(FF_HEADER_LEN + 33);
	const o = writeHeader(fixed, msg);
	msg.sNextPerCommitmentPoint.copy(fixed, o);

	const records: ITlvRecord[] = [];
	if (msg.revocationSecretN0) {
		if (msg.revocationSecretN0.length !== 32) {
			throw new Error('revocation_secret_n0 must be 32 bytes');
		}
		records.push({
			type: FF_RECONCILE_ACK_TLV_SECRET_N0,
			value: msg.revocationSecretN0
		});
	}
	if (msg.revocationSecretN0Plus1) {
		if (msg.revocationSecretN0Plus1.length !== 32) {
			throw new Error('revocation_secret_n0plus1 must be 32 bytes');
		}
		records.push({
			type: FF_RECONCILE_ACK_TLV_SECRET_N0_PLUS_1,
			value: msg.revocationSecretN0Plus1
		});
	}
	return Buffer.concat([fixed, encodeTlvStream(records)]);
}

export function decodeFforReconcileAckMessage(
	payload: Buffer
): IFforReconcileAckMessage {
	const header = readHeader(payload, 'ff_reconcile_ack');
	if (payload.length < FF_HEADER_LEN + 33) {
		throw new Error(`ff_reconcile_ack too short: got ${payload.length}`);
	}
	const sNextPerCommitmentPoint = Buffer.from(
		payload.subarray(FF_HEADER_LEN, FF_HEADER_LEN + 33)
	);
	const { records } = decodeTlvStream(
		payload.subarray(FF_HEADER_LEN + 33),
		0,
		FF_RECONCILE_ACK_KNOWN_TLVS
	);
	const s0 = findTlvRecord(records, FF_RECONCILE_ACK_TLV_SECRET_N0);
	if (s0 && s0.length !== 32) {
		throw new Error('ff_reconcile_ack revocation_secret_n0 must be 32 bytes');
	}
	const s1 = findTlvRecord(records, FF_RECONCILE_ACK_TLV_SECRET_N0_PLUS_1);
	if (s1 && s1.length !== 32) {
		throw new Error(
			'ff_reconcile_ack revocation_secret_n0plus1 must be 32 bytes'
		);
	}
	return {
		channelId: header.channelId,
		epochId: header.epochId,
		sNextPerCommitmentPoint,
		revocationSecretN0: s0 ? Buffer.from(s0) : undefined,
		revocationSecretN0Plus1: s1 ? Buffer.from(s1) : undefined
	};
}

// ---- ff_revoke_batch (55019, R→S) — spec §11.1 step 4 ----

/** R's per-commitment secrets for its skipped indexes n_R … n_R + j − 1. */
export interface IFforRevokeBatchMessage extends IFforHeader {
	secrets: Buffer[];
}

export function encodeFforRevokeBatchMessage(
	msg: IFforRevokeBatchMessage
): Buffer {
	if (msg.secrets.length > 0xffff) {
		throw new Error('too many secrets');
	}
	for (const s of msg.secrets) {
		if (s.length !== 32) {
			throw new Error('per-commitment secret must be 32 bytes');
		}
	}
	const fixed = Buffer.alloc(FF_HEADER_LEN + 2);
	const o = writeHeader(fixed, msg);
	fixed.writeUInt16BE(msg.secrets.length, o);
	return Buffer.concat([fixed, ...msg.secrets]);
}

export function decodeFforRevokeBatchMessage(
	payload: Buffer
): IFforRevokeBatchMessage {
	const header = readHeader(payload, 'ff_revoke_batch');
	if (payload.length < FF_HEADER_LEN + 2) {
		throw new Error(`ff_revoke_batch too short: got ${payload.length}`);
	}
	const count = payload.readUInt16BE(FF_HEADER_LEN);
	let o = FF_HEADER_LEN + 2;
	if (payload.length < o + count * 32) {
		throw new Error('ff_revoke_batch truncated in secrets');
	}
	const secrets: Buffer[] = [];
	for (let i = 0; i < count; i++) {
		secrets.push(Buffer.from(payload.subarray(o, o + 32)));
		o += 32;
	}
	return { channelId: header.channelId, epochId: header.epochId, secrets };
}
