/**
 * FFOR: Fast-Forward Offline Receive — wire codecs (spec §7, §11.1, §14).
 *
 * All messages use odd types in the custom range (55001–55023) so they are
 * ignorable by non-implementing peers. All multi-byte integers are big-endian.
 * Every message body begins `[32: channel_id][32: epoch_id]`.
 *
 * Signed messages (ff_init, ff_accept — spec §7 "✍"): the `signature` field is
 * the FINAL 64 bytes of the message body. The node-key signature is computed
 * over the SHA256 of:
 *
 *     [2: message type (big-endian)] || [body bytes excluding the final 64]
 *
 * i.e. the digest covers the type plus every body byte that precedes the
 * signature (including the TLV stream, which sits between the fixed fields and
 * the signature). These signatures exist for non-repudiation (fraud proofs,
 * spec §12.2), since Noise transport authenticates but does not produce
 * third-party-verifiable evidence.
 */

import crypto from 'crypto';
import { sign, verify } from '../crypto/ecdh';
import {
	encodeTlvStream,
	decodeTlvStream,
	findTlvRecord,
	ITlvRecord
} from '../message/tlv';

// ---- Message type ids (spec §14, provisional pending bLIP assignment) ----

export const FF_INIT_TYPE = 55001;
export const FF_ACCEPT_TYPE = 55003;
export const FF_INVOICES_TYPE = 55005;
export const FF_ESCAPE_SIGS_TYPE = 55009;
export const FF_BEGIN_TYPE = 55011;
export const FF_END_TYPE = 55021;
export const FF_ERROR_TYPE = 55023;

/** [32: channel_id][32: epoch_id] prefix common to every FFOR message. */
const FF_HEADER_LEN = 64;
const SIG_LEN = 64;

// ---- Interfaces ----

export interface IFforHeader {
	channelId: Buffer;
	epochId: Buffer;
}

/** ff_init (55001, R→S) ✍ — spec §7.1. */
export interface IFforInitMessage extends IFforHeader {
	variant: number;
	budgetMsat: bigint;
	maxPayments: number;
	minPaymentMsat: bigint;
	settlementDeadline: number;
	voucherExpiry: number;
	feeBaseMsat: number;
	feeProportionalMillionths: number;
	escapeGranularityMsat: bigint;
	rPerCommitmentPoints: Buffer[];
	/** TLV 1 — Variant B only: hashes generated by R's tower (K×32). */
	paymentHashes?: Buffer[];
	/** TLV 3 — Variant B only. */
	towerNodeId?: Buffer;
	/** TLV 5 — Variant B only. */
	towerUri?: string;
	/** R's node-key signature (final 64 bytes of the body). */
	signature: Buffer;
}

/** ff_accept (55003, S→R) ✍ — spec §7.2. */
export interface IFforAcceptMessage extends IFforHeader {
	/** `n0`: S's commitment number at epoch start (explicit, anchors evidence). */
	sCommitmentNumber: bigint;
	/** TLV 1 — Variant A only: S-generated hashes (K×32). */
	paymentHashes?: Buffer[];
	/** S's node-key signature (final 64 bytes of the body). */
	signature: Buffer;
}

/** ff_invoices (55005, R→S) — spec §7.3. */
export interface IFforInvoicesMessage extends IFforHeader {
	/** Length-prefixed BOLT 11 strings; count MUST equal K. */
	invoices: string[];
}

/** ff_escape_sigs (55009, R→S) — spec §7.4, optional iff G > 0. */
export interface IFforEscapeSigsMessage extends IFforHeader {
	/** R's signatures on escape commitments E_1…E_J, J = ceil(budget/G). */
	escapeSigs: Buffer[];
	/**
	 * R's signatures for the aggregate voucher spend path on each E_j —
	 * "not required in v1 (bare-sig voucher, §10), reserved". Encoded only when
	 * provided; tolerated as absent on decode.
	 */
	escapeHtlcSigs?: Buffer[];
}

/** ff_begin (55011, R→S) — spec §7.5. */
export interface IFforBeginMessage extends IFforHeader {
	/** For audit; MUST be within a few blocks of the current tip. */
	epochStartHeight: number;
}

/** ff_end (55021, both directions) — spec §11.1 step 5. Header only. */
export type IFforEndMessage = IFforHeader;

/** ff_error (55023, both directions) — spec §11.1. */
export interface IFforErrorMessage extends IFforHeader {
	/** Free-form diagnostic, `[2: len][len: data]` (BOLT 1 error style). */
	data: Buffer;
}

// ---- Signature helpers ----

/**
 * Digest a signed FFOR message: SHA256 over the 2-byte big-endian message type
 * followed by every body byte preceding the final-64-byte signature field.
 */
export function fforMessageDigest(type: number, payload: Buffer): Buffer {
	if (payload.length < FF_HEADER_LEN + SIG_LEN) {
		throw new Error('FFOR signed message too short to digest');
	}
	const typeBuf = Buffer.alloc(2);
	typeBuf.writeUInt16BE(type, 0);
	return crypto
		.createHash('sha256')
		.update(typeBuf)
		.update(payload.subarray(0, payload.length - SIG_LEN))
		.digest();
}

/**
 * Sign an encoded FFOR message body in place: computes the digest (which by
 * construction excludes the final 64 bytes) and writes the node-key signature
 * into those final 64 bytes. Returns the same buffer for chaining.
 */
export function signFforMessage(
	type: number,
	payload: Buffer,
	nodePrivateKey: Buffer
): Buffer {
	const sig = sign(fforMessageDigest(type, payload), nodePrivateKey);
	sig.copy(payload, payload.length - SIG_LEN);
	return payload;
}

/** Verify the node-key signature carried in an encoded FFOR message body. */
export function verifyFforMessageSignature(
	type: number,
	payload: Buffer,
	nodeId: Buffer
): boolean {
	if (payload.length < FF_HEADER_LEN + SIG_LEN) return false;
	try {
		return verify(
			fforMessageDigest(type, payload),
			nodeId,
			payload.subarray(payload.length - SIG_LEN)
		);
	} catch {
		return false;
	}
}

// ---- Common helpers ----

function writeHeader(buf: Buffer, msg: IFforHeader): number {
	if (msg.channelId.length !== 32) {
		throw new Error(`channel_id must be 32 bytes, got ${msg.channelId.length}`);
	}
	if (msg.epochId.length !== 32) {
		throw new Error(`epoch_id must be 32 bytes, got ${msg.epochId.length}`);
	}
	msg.channelId.copy(buf, 0);
	msg.epochId.copy(buf, 32);
	return FF_HEADER_LEN;
}

function readHeader(
	payload: Buffer,
	name: string
): { channelId: Buffer; epochId: Buffer } {
	if (payload.length < FF_HEADER_LEN) {
		throw new Error(
			`${name} too short: need at least ${FF_HEADER_LEN} bytes, got ${payload.length}`
		);
	}
	return {
		channelId: Buffer.from(payload.subarray(0, 32)),
		epochId: Buffer.from(payload.subarray(32, 64))
	};
}

/**
 * Decode just the `[channel_id][epoch_id]` prefix — used by the manager to
 * route an FFOR message to its channel before full decoding.
 */
export function decodeFforHeader(payload: Buffer): IFforHeader {
	return readHeader(payload, 'FFOR message');
}

/** Split a concatenated K×32 hash blob into 32-byte Buffers. */
function splitHashes(value: Buffer, tlvName: string): Buffer[] {
	if (value.length === 0 || value.length % 32 !== 0) {
		throw new Error(
			`${tlvName}: length must be a positive multiple of 32, got ${value.length}`
		);
	}
	const hashes: Buffer[] = [];
	for (let i = 0; i < value.length; i += 32) {
		hashes.push(Buffer.from(value.subarray(i, i + 32)));
	}
	return hashes;
}

// ---- ff_init (55001) ----

const FF_INIT_TLV_PAYMENT_HASHES = 1n;
const FF_INIT_TLV_TOWER_NODE_ID = 3n;
const FF_INIT_TLV_TOWER_URI = 5n;
const FF_INIT_KNOWN_TLVS = new Set<bigint>([
	FF_INIT_TLV_PAYMENT_HASHES,
	FF_INIT_TLV_TOWER_NODE_ID,
	FF_INIT_TLV_TOWER_URI
]);

/**
 * Encode ff_init. `msg.signature` may be a 64-byte placeholder (e.g. zeros)
 * that the caller overwrites via signFforMessage().
 */
export function encodeFforInitMessage(msg: IFforInitMessage): Buffer {
	if (msg.signature.length !== SIG_LEN) {
		throw new Error(`signature must be 64 bytes, got ${msg.signature.length}`);
	}
	for (const p of msg.rPerCommitmentPoints) {
		if (p.length !== 33) {
			throw new Error(`per-commitment point must be 33 bytes, got ${p.length}`);
		}
	}
	if (msg.rPerCommitmentPoints.length > 0xffff) {
		throw new Error('too many per-commitment points');
	}

	// Fixed fields after the header: 1+8+2+8+4+4+4+4+8 = 43 bytes, then
	// [2: num_points][num_points × 33].
	const fixed = Buffer.alloc(
		FF_HEADER_LEN + 43 + 2 + msg.rPerCommitmentPoints.length * 33
	);
	let o = writeHeader(fixed, msg);
	fixed.writeUInt8(msg.variant, o);
	o += 1;
	fixed.writeBigUInt64BE(msg.budgetMsat, o);
	o += 8;
	fixed.writeUInt16BE(msg.maxPayments, o);
	o += 2;
	fixed.writeBigUInt64BE(msg.minPaymentMsat, o);
	o += 8;
	fixed.writeUInt32BE(msg.settlementDeadline, o);
	o += 4;
	fixed.writeUInt32BE(msg.voucherExpiry, o);
	o += 4;
	fixed.writeUInt32BE(msg.feeBaseMsat, o);
	o += 4;
	fixed.writeUInt32BE(msg.feeProportionalMillionths, o);
	o += 4;
	fixed.writeBigUInt64BE(msg.escapeGranularityMsat, o);
	o += 8;
	fixed.writeUInt16BE(msg.rPerCommitmentPoints.length, o);
	o += 2;
	for (const p of msg.rPerCommitmentPoints) {
		p.copy(fixed, o);
		o += 33;
	}

	const records: ITlvRecord[] = [];
	if (msg.paymentHashes && msg.paymentHashes.length > 0) {
		records.push({
			type: FF_INIT_TLV_PAYMENT_HASHES,
			value: Buffer.concat(msg.paymentHashes)
		});
	}
	if (msg.towerNodeId) {
		if (msg.towerNodeId.length !== 33) {
			throw new Error(
				`tower_node_id must be 33 bytes, got ${msg.towerNodeId.length}`
			);
		}
		records.push({ type: FF_INIT_TLV_TOWER_NODE_ID, value: msg.towerNodeId });
	}
	if (msg.towerUri !== undefined) {
		records.push({
			type: FF_INIT_TLV_TOWER_URI,
			value: Buffer.from(msg.towerUri, 'utf8')
		});
	}

	return Buffer.concat([fixed, encodeTlvStream(records), msg.signature]);
}

export function decodeFforInitMessage(payload: Buffer): IFforInitMessage {
	const header = readHeader(payload, 'ff_init');
	// header(64) + fixed(43) + num_points(2) + signature(64)
	if (payload.length < FF_HEADER_LEN + 43 + 2 + SIG_LEN) {
		throw new Error(`ff_init too short: got ${payload.length}`);
	}
	let o = FF_HEADER_LEN;
	const variant = payload.readUInt8(o);
	o += 1;
	const budgetMsat = payload.readBigUInt64BE(o);
	o += 8;
	const maxPayments = payload.readUInt16BE(o);
	o += 2;
	const minPaymentMsat = payload.readBigUInt64BE(o);
	o += 8;
	const settlementDeadline = payload.readUInt32BE(o);
	o += 4;
	const voucherExpiry = payload.readUInt32BE(o);
	o += 4;
	const feeBaseMsat = payload.readUInt32BE(o);
	o += 4;
	const feeProportionalMillionths = payload.readUInt32BE(o);
	o += 4;
	const escapeGranularityMsat = payload.readBigUInt64BE(o);
	o += 8;
	const numPoints = payload.readUInt16BE(o);
	o += 2;
	if (payload.length < o + numPoints * 33 + SIG_LEN) {
		throw new Error('ff_init truncated in r_per_commitment_points');
	}
	const rPerCommitmentPoints: Buffer[] = [];
	for (let i = 0; i < numPoints; i++) {
		rPerCommitmentPoints.push(Buffer.from(payload.subarray(o, o + 33)));
		o += 33;
	}

	// Everything between the points and the final-64-byte signature is TLV.
	const tlvEnd = payload.length - SIG_LEN;
	const { records } = decodeTlvStream(
		payload.subarray(o, tlvEnd),
		0,
		FF_INIT_KNOWN_TLVS
	);
	const hashBlob = findTlvRecord(records, FF_INIT_TLV_PAYMENT_HASHES);
	const towerNodeId = findTlvRecord(records, FF_INIT_TLV_TOWER_NODE_ID);
	if (towerNodeId && towerNodeId.length !== 33) {
		throw new Error(
			`ff_init tower_node_id must be 33 bytes, got ${towerNodeId.length}`
		);
	}
	const towerUriBuf = findTlvRecord(records, FF_INIT_TLV_TOWER_URI);

	return {
		channelId: header.channelId,
		epochId: header.epochId,
		variant,
		budgetMsat,
		maxPayments,
		minPaymentMsat,
		settlementDeadline,
		voucherExpiry,
		feeBaseMsat,
		feeProportionalMillionths,
		escapeGranularityMsat,
		rPerCommitmentPoints,
		paymentHashes: hashBlob
			? splitHashes(hashBlob, 'ff_init payment_hashes')
			: undefined,
		towerNodeId: towerNodeId ? Buffer.from(towerNodeId) : undefined,
		towerUri: towerUriBuf ? towerUriBuf.toString('utf8') : undefined,
		signature: Buffer.from(payload.subarray(tlvEnd))
	};
}

// ---- ff_accept (55003) ----

const FF_ACCEPT_TLV_PAYMENT_HASHES = 1n;
const FF_ACCEPT_KNOWN_TLVS = new Set<bigint>([FF_ACCEPT_TLV_PAYMENT_HASHES]);

export function encodeFforAcceptMessage(msg: IFforAcceptMessage): Buffer {
	if (msg.signature.length !== SIG_LEN) {
		throw new Error(`signature must be 64 bytes, got ${msg.signature.length}`);
	}
	const fixed = Buffer.alloc(FF_HEADER_LEN + 8);
	const o = writeHeader(fixed, msg);
	fixed.writeBigUInt64BE(msg.sCommitmentNumber, o);

	const records: ITlvRecord[] = [];
	if (msg.paymentHashes && msg.paymentHashes.length > 0) {
		records.push({
			type: FF_ACCEPT_TLV_PAYMENT_HASHES,
			value: Buffer.concat(msg.paymentHashes)
		});
	}

	return Buffer.concat([fixed, encodeTlvStream(records), msg.signature]);
}

export function decodeFforAcceptMessage(payload: Buffer): IFforAcceptMessage {
	const header = readHeader(payload, 'ff_accept');
	if (payload.length < FF_HEADER_LEN + 8 + SIG_LEN) {
		throw new Error(`ff_accept too short: got ${payload.length}`);
	}
	const sCommitmentNumber = payload.readBigUInt64BE(FF_HEADER_LEN);
	const tlvEnd = payload.length - SIG_LEN;
	const { records } = decodeTlvStream(
		payload.subarray(FF_HEADER_LEN + 8, tlvEnd),
		0,
		FF_ACCEPT_KNOWN_TLVS
	);
	const hashBlob = findTlvRecord(records, FF_ACCEPT_TLV_PAYMENT_HASHES);

	return {
		channelId: header.channelId,
		epochId: header.epochId,
		sCommitmentNumber,
		paymentHashes: hashBlob
			? splitHashes(hashBlob, 'ff_accept payment_hashes')
			: undefined,
		signature: Buffer.from(payload.subarray(tlvEnd))
	};
}

// ---- ff_invoices (55005) ----

export function encodeFforInvoicesMessage(msg: IFforInvoicesMessage): Buffer {
	if (msg.invoices.length > 0xffff) {
		throw new Error('too many invoices');
	}
	const parts: Buffer[] = [];
	const fixed = Buffer.alloc(FF_HEADER_LEN + 2);
	const o = writeHeader(fixed, msg);
	fixed.writeUInt16BE(msg.invoices.length, o);
	parts.push(fixed);
	for (const inv of msg.invoices) {
		const b = Buffer.from(inv, 'utf8');
		if (b.length > 0xffff) {
			throw new Error('invoice string too long');
		}
		const len = Buffer.alloc(2);
		len.writeUInt16BE(b.length, 0);
		parts.push(len, b);
	}
	return Buffer.concat(parts);
}

export function decodeFforInvoicesMessage(
	payload: Buffer
): IFforInvoicesMessage {
	const header = readHeader(payload, 'ff_invoices');
	if (payload.length < FF_HEADER_LEN + 2) {
		throw new Error(`ff_invoices too short: got ${payload.length}`);
	}
	let o = FF_HEADER_LEN;
	const num = payload.readUInt16BE(o);
	o += 2;
	const invoices: string[] = [];
	for (let i = 0; i < num; i++) {
		if (o + 2 > payload.length) {
			throw new Error('ff_invoices truncated in invoice length');
		}
		const len = payload.readUInt16BE(o);
		o += 2;
		if (o + len > payload.length) {
			throw new Error('ff_invoices truncated in invoice body');
		}
		invoices.push(payload.subarray(o, o + len).toString('utf8'));
		o += len;
	}
	return { channelId: header.channelId, epochId: header.epochId, invoices };
}

// ---- ff_escape_sigs (55009) ----

export function encodeFforEscapeSigsMessage(
	msg: IFforEscapeSigsMessage
): Buffer {
	const j = msg.escapeSigs.length;
	if (j > 0xffff) {
		throw new Error('too many escape sigs');
	}
	for (const s of msg.escapeSigs) {
		if (s.length !== SIG_LEN) {
			throw new Error(`escape sig must be 64 bytes, got ${s.length}`);
		}
	}
	if (msg.escapeHtlcSigs) {
		if (msg.escapeHtlcSigs.length !== j) {
			throw new Error(
				`escape_htlc_sigs count ${msg.escapeHtlcSigs.length} != num_escapes ${j}`
			);
		}
		for (const s of msg.escapeHtlcSigs) {
			if (s.length !== SIG_LEN) {
				throw new Error(`escape HTLC sig must be 64 bytes, got ${s.length}`);
			}
		}
	}

	const fixed = Buffer.alloc(FF_HEADER_LEN + 2);
	const o = writeHeader(fixed, msg);
	fixed.writeUInt16BE(j, o);
	return Buffer.concat([
		fixed,
		...msg.escapeSigs,
		...(msg.escapeHtlcSigs ?? [])
	]);
}

export function decodeFforEscapeSigsMessage(
	payload: Buffer
): IFforEscapeSigsMessage {
	const header = readHeader(payload, 'ff_escape_sigs');
	if (payload.length < FF_HEADER_LEN + 2) {
		throw new Error(`ff_escape_sigs too short: got ${payload.length}`);
	}
	let o = FF_HEADER_LEN;
	const j = payload.readUInt16BE(o);
	o += 2;
	if (payload.length < o + j * SIG_LEN) {
		throw new Error('ff_escape_sigs truncated in escape_sigs');
	}
	const escapeSigs: Buffer[] = [];
	for (let i = 0; i < j; i++) {
		escapeSigs.push(Buffer.from(payload.subarray(o, o + SIG_LEN)));
		o += SIG_LEN;
	}
	// escape_htlc_sigs are reserved in v1 — tolerate their absence.
	let escapeHtlcSigs: Buffer[] | undefined;
	if (payload.length >= o + j * SIG_LEN && j > 0) {
		escapeHtlcSigs = [];
		for (let i = 0; i < j; i++) {
			escapeHtlcSigs.push(Buffer.from(payload.subarray(o, o + SIG_LEN)));
			o += SIG_LEN;
		}
	}
	return {
		channelId: header.channelId,
		epochId: header.epochId,
		escapeSigs,
		escapeHtlcSigs
	};
}

// ---- ff_begin (55011) ----

export function encodeFforBeginMessage(msg: IFforBeginMessage): Buffer {
	const buf = Buffer.alloc(FF_HEADER_LEN + 4);
	const o = writeHeader(buf, msg);
	buf.writeUInt32BE(msg.epochStartHeight, o);
	return buf;
}

export function decodeFforBeginMessage(payload: Buffer): IFforBeginMessage {
	const header = readHeader(payload, 'ff_begin');
	if (payload.length < FF_HEADER_LEN + 4) {
		throw new Error(`ff_begin too short: got ${payload.length}`);
	}
	return {
		channelId: header.channelId,
		epochId: header.epochId,
		epochStartHeight: payload.readUInt32BE(FF_HEADER_LEN)
	};
}

// ---- ff_end (55021) ----

export function encodeFforEndMessage(msg: IFforEndMessage): Buffer {
	const buf = Buffer.alloc(FF_HEADER_LEN);
	writeHeader(buf, msg);
	return buf;
}

export function decodeFforEndMessage(payload: Buffer): IFforEndMessage {
	return readHeader(payload, 'ff_end');
}

// ---- ff_error (55023) ----

export function encodeFforErrorMessage(msg: IFforErrorMessage): Buffer {
	if (msg.data.length > 0xffff) {
		throw new Error('ff_error data too long');
	}
	const buf = Buffer.alloc(FF_HEADER_LEN + 2 + msg.data.length);
	let o = writeHeader(buf, msg);
	buf.writeUInt16BE(msg.data.length, o);
	o += 2;
	msg.data.copy(buf, o);
	return buf;
}

export function decodeFforErrorMessage(payload: Buffer): IFforErrorMessage {
	const header = readHeader(payload, 'ff_error');
	if (payload.length < FF_HEADER_LEN + 2) {
		throw new Error(`ff_error too short: got ${payload.length}`);
	}
	const len = payload.readUInt16BE(FF_HEADER_LEN);
	if (payload.length < FF_HEADER_LEN + 2 + len) {
		throw new Error('ff_error truncated in data');
	}
	return {
		channelId: header.channelId,
		epochId: header.epochId,
		data: Buffer.from(
			payload.subarray(FF_HEADER_LEN + 2, FF_HEADER_LEN + 2 + len)
		)
	};
}
