/**
 * FFOR M4 — the Variant B tower `T` (spec §9.4).
 *
 * A standalone agent chosen by R that holds preimages hostage against valid
 * settlement packages, stores the packages, serves them back to R on
 * authenticated request, and watches for a revoked C_{n0}^S broadcast. It
 * holds NO funds and (except the scoped §9.4 option (a) revocation secret)
 * no channel keys.
 *
 * By design this module has ZERO coupling to ChannelManager/Channel: it is
 * provisioned with plain data, synthesizes its own read-only mirror of the
 * channel state, and talks to the world only through IFforTowerClient (the
 * transport is out of scope per the spec — an in-process loopback lives here
 * for tests, and example/ffor-tower.ts runs the same object standalone).
 *
 * NOTE (spec §9.4 provisioning erratum): the spec's provisioning list omits
 * several items the checklist cannot run without — the pre-epoch balances and
 * commitment numbers (deterministic C_i^R reconstruction), the full channel
 * configs (the §8 reserve/in-flight/slot checks), the channel_type, R's
 * channel role, and S's NODE id (the package signature is S's node-key sig
 * and is unverifiable without it). IFforTowerProvisioning carries the
 * superset.
 */

import crypto from 'crypto';
import * as bitcoin from 'bitcoinjs-lib';
import { IChannelState } from '../channel/channel-state';
import {
	createOpenerState,
	createAcceptorState
} from '../channel/channel-state';
import { ChannelState, IChannelConfig } from '../channel/types';
import { IChannelBasepoints } from '../keys/derivation';
import { ChannelSigner } from '../keys/signer';
import { sign, verify, getPublicKey } from '../crypto/ecdh';
import { MAX_INDEX } from '../keys/shachain';
import { FforEpochState, IFforEpochParams, IFforEpochStateData } from './types';
import {
	decodeFforSettlementMessage,
	IFforSettlementMessage
} from './messages';
import { validateSettlementPackage } from './settlement';
import {
	classifyCommitmentTx,
	classifyOutputs,
	resolveRevokedCommitmentOutputs
} from '../chain/output-resolver';
import { CommitmentType, OutputType } from '../chain/types';

// ─────────────── Provisioning (spec §9.4, plus the erratum superset) ───────────────

export interface IFforTowerChannelStatics {
	/** Funding outpoint (txid in internal byte order, as serialized in txs). */
	fundingTxid: Buffer;
	fundingOutputIndex: number;
	fundingSatoshis: bigint;
	/** Negotiated channel_type (anchors, spec §5). */
	channelType: Buffer;
	/** Whether R is the channel opener (funder). */
	rIsOpener: boolean;
	rBasepoints: IChannelBasepoints;
	sBasepoints: IChannelBasepoints;
	/** Both sides' configs: dust_limit, to_self_delay, reserve, slots, feerate. */
	rConfig: IChannelConfig;
	sConfig: IChannelConfig;
	/** The last co-signed pre-epoch balances (base state of every C_i^R). */
	preEpochRLocalMsat: bigint;
	preEpochSLocalMsat: bigint;
	/** n_R and n0: both sides' commitment numbers at epoch start. */
	nR: bigint;
	n0: bigint;
	/** S's per-commitment point at n0 (anchors the seq-1 pre-revocation). */
	sPerCommitmentPointN0: Buffer;
	/** The frozen epoch feerate (spec §5). */
	frozenFeeratePerKw: number;
}

export interface IFforTowerProvisioning {
	epochId: Buffer;
	/** Epoch parameters incl. the hash set H_1..H_K and R's pre-shared points. */
	params: IFforEpochParams;
	/** The preimages t_1..t_K (generated by T or by R and handed over). */
	preimages: Buffer[];
	channel: IFforTowerChannelStatics;
	/** Authenticates R's fetches (spec §9.4 "authenticated request"). */
	rNodeId: Buffer;
	/** Verifies S's package signatures (spec §9.4 erratum: unlisted but required). */
	sNodeId: Buffer;
	/**
	 * Spec §9.4 penalty option (a): R's SCOPED revocation basepoint secret plus
	 * a mandated sweep script. A malicious T can redirect only penalty funds,
	 * and only if S also broadcast a revoked state (the standard watchtower
	 * compromise). Omit both for alert-only towers (option (b)).
	 */
	revocationBasepointSecret?: Buffer;
	sweepScript?: Buffer;
	network?: bitcoin.Network;
}

// ─────────────── Durable store ───────────────

/** Everything the tower must never lose once a preimage has been released. */
export interface IFforTowerRecord {
	epochIdHex: string;
	lastReleased: number;
	/** Raw ff_settlement payloads, seq-1 indexed (signed evidence, §12.2). */
	packagesHex: string[];
	/** per_commitment_secret_S[n0], captured from package 1 (breach watch). */
	revocationSecretN0Hex: string | null;
}

/**
 * Durable storage hook. save() MUST complete before the corresponding
 * preimage release returns (spec §9.4 checklist item 5: "Package stored
 * durably. Only then release t_i").
 */
export interface IFforTowerStore {
	save(record: IFforTowerRecord): void;
	load(epochIdHex: string): IFforTowerRecord | null;
}

/** In-memory store; records the order of operations for tests. */
export class MemoryTowerStore implements IFforTowerStore {
	records = new Map<string, IFforTowerRecord>();
	saveLog: Array<{ epochIdHex: string; lastReleased: number }> = [];

	save(record: IFforTowerRecord): void {
		this.records.set(record.epochIdHex, {
			...record,
			packagesHex: [...record.packagesHex]
		});
		this.saveLog.push({
			epochIdHex: record.epochIdHex,
			lastReleased: record.lastReleased
		});
	}

	load(epochIdHex: string): IFforTowerRecord | null {
		return this.records.get(epochIdHex) ?? null;
	}
}

// ─────────────── Wire-ish result types ───────────────

/** ff_release {seq, preimage} (spec §9.2 — transport-defined). */
export type IFforTowerReleaseResult =
	| { ok: true; seq: number; preimage: Buffer }
	| { ok: false; error: string };

export interface IFforTowerFetchRequest {
	epochId: Buffer;
	/** Caller-chosen nonce; the signature covers it. */
	nonce: Buffer;
	/** R's node-key signature over towerFetchDigest(epochId, nonce). */
	signature: Buffer;
}

export interface IFforTowerFetchResponse {
	ok: boolean;
	error?: string;
	lastReleased: number;
	/** Raw ff_settlement payloads 1..lastReleased. */
	packages: Buffer[];
	/** Preimages t_1..t_lastReleased (each verified released). */
	preimages: Buffer[];
}

export interface IFforTowerBreachResult {
	breach: boolean;
	/** Human-readable alert (always set on breach — option (b) minimum). */
	alert?: string;
	/** Option (a): fully-witnessed justice transaction(s), ready to broadcast. */
	justiceTxs: Buffer[];
}

/** Digest R signs to authenticate a fetch. */
export function towerFetchDigest(epochId: Buffer, nonce: Buffer): Buffer {
	return crypto
		.createHash('sha256')
		.update(Buffer.from('ffor/tower/fetch'))
		.update(epochId)
		.update(nonce)
		.digest();
}

/** R side: build an authenticated fetch request. */
export function buildTowerFetchRequest(
	epochId: Buffer,
	rNodePrivateKey: Buffer
): IFforTowerFetchRequest {
	const nonce = crypto.randomBytes(32);
	return {
		epochId,
		nonce,
		signature: sign(towerFetchDigest(epochId, nonce), rNodePrivateKey)
	};
}

// ─────────────── The tower ───────────────

export class FforTower {
	private _prov: IFforTowerProvisioning | null = null;
	private _record: IFforTowerRecord | null = null;
	private _store: IFforTowerStore;
	/** The tower's view of the epoch, mirroring R's (fed to the §9.4 checklist). */
	private _epochView: IFforEpochStateData | null = null;
	private _currentBlockHeight = 0;

	constructor(store?: IFforTowerStore) {
		this._store = store ?? new MemoryTowerStore();
	}

	/** The tower's chain view (drives the height < D checklist item). */
	setBlockHeight(height: number): void {
		this._currentBlockHeight = height;
	}

	get lastReleased(): number {
		return this._record?.lastReleased ?? 0;
	}

	/** R provisions the tower BEFORE ff_init (spec §9.4). */
	provision(p: IFforTowerProvisioning): void {
		if (!p.params.paymentHashes || p.params.paymentHashes.length === 0) {
			throw new Error('tower provisioning requires the payment hash set');
		}
		if (p.preimages.length !== p.params.paymentHashes.length) {
			throw new Error('tower provisioning: preimage count != hash count');
		}
		for (let i = 0; i < p.preimages.length; i++) {
			const h = crypto.createHash('sha256').update(p.preimages[i]).digest();
			if (!h.equals(p.params.paymentHashes[i])) {
				throw new Error(`tower provisioning: SHA256(t_${i + 1}) != H_${i + 1}`);
			}
		}
		this._prov = p;
		const epochIdHex = p.epochId.toString('hex');
		this._record = this._store.load(epochIdHex) ?? {
			epochIdHex,
			lastReleased: 0,
			packagesHex: [],
			revocationSecretN0Hex: null
		};
		this._epochView = this._buildEpochView();
		// Replay any previously stored packages through the view so the
		// deterministic reconstruction state matches after a tower restart.
		for (let i = 0; i < this._record.lastReleased; i++) {
			const msg = decodeFforSettlementMessage(
				Buffer.from(this._record.packagesHex[i], 'hex')
			);
			this._epochView.htlcAmountsMsat[i] = msg.htlcAmountMsat;
			this._epochView.voucherAmountsMsat[i] = msg.voucherAmountMsat;
			this._epochView.lastSeq = msg.seq;
		}
	}

	/**
	 * S requests a preimage release for a settlement package (spec §9.2
	 * variant B step 2). Runs the full §9.4 verification checklist; on success
	 * the package is DURABLY STORED FIRST, and only then is t_i returned.
	 * Idempotent by seq: a byte-identical re-request (S crash replay) returns
	 * the same preimage; a DIFFERING package for a released seq is rejected
	 * (the two signed copies are themselves evidence, §12.2).
	 */
	handleReleaseRequest(payload: Buffer): IFforTowerReleaseResult {
		if (!this._prov || !this._record || !this._epochView) {
			return { ok: false, error: 'tower not provisioned' };
		}
		let msg: IFforSettlementMessage;
		try {
			msg = decodeFforSettlementMessage(payload);
		} catch (e) {
			return {
				ok: false,
				error: `undecodable package: ${(e as Error).message}`
			};
		}
		if (!msg.epochId.equals(this._prov.epochId)) {
			return { ok: false, error: 'unknown epoch_id' };
		}

		// Idempotent replay of an already-released seq.
		if (msg.seq >= 1 && msg.seq <= this._record.lastReleased) {
			const stored = Buffer.from(this._record.packagesHex[msg.seq - 1], 'hex');
			if (stored.equals(payload)) {
				return {
					ok: true,
					seq: msg.seq,
					preimage: Buffer.from(this._prov.preimages[msg.seq - 1])
				};
			}
			return {
				ok: false,
				error: `package ${msg.seq} differs from the stored copy (signed evidence)`
			};
		}

		// §9.4 checklist 1-4 (strictly-next seq, hash, height < D, amounts,
		// deterministic reconstruction + both signature sets, seq-1 secret
		// binding) — the same code path R uses (shared, not duplicated).
		const result = validateSettlementPackage({
			base: this._buildMirrorState(),
			signer: this._verifyOnlySigner(),
			epoch: this._epochView,
			payload,
			remoteNodeId: this._prov.sNodeId,
			sPerCommitmentPointN0: this._prov.channel.sPerCommitmentPointN0,
			currentBlockHeight: this._currentBlockHeight
		});
		if (!result.ok || !result.msg) {
			return { ok: false, error: result.error ?? 'invalid package' };
		}

		// Checklist 5: package stored durably. ONLY THEN release t_i.
		this._record.packagesHex[msg.seq - 1] = payload.toString('hex');
		if (msg.seq === 1 && msg.revocationSecretN0) {
			this._record.revocationSecretN0Hex =
				msg.revocationSecretN0.toString('hex');
		}
		this._record.lastReleased = msg.seq;
		this._store.save(this._record);
		this._epochView.lastSeq = msg.seq;

		return {
			ok: true,
			seq: msg.seq,
			preimage: Buffer.from(this._prov.preimages[msg.seq - 1])
		};
	}

	/**
	 * R fetches everything back (spec §9.4 "serve stored packages and
	 * preimages to R on authenticated request").
	 */
	handleFetch(req: IFforTowerFetchRequest): IFforTowerFetchResponse {
		const fail = (error: string): IFforTowerFetchResponse => ({
			ok: false,
			error,
			lastReleased: 0,
			packages: [],
			preimages: []
		});
		if (!this._prov || !this._record) {
			return fail('tower not provisioned');
		}
		if (!req.epochId.equals(this._prov.epochId)) {
			return fail('unknown epoch_id');
		}
		let authed = false;
		try {
			authed = verify(
				towerFetchDigest(req.epochId, req.nonce),
				this._prov.rNodeId,
				req.signature
			);
		} catch {
			authed = false;
		}
		if (!authed) {
			return fail('fetch authentication failed (not signed by R)');
		}
		const n = this._record.lastReleased;
		return {
			ok: true,
			lastReleased: n,
			packages: this._record.packagesHex
				.slice(0, n)
				.map((h) => Buffer.from(h, 'hex')),
			preimages: this._prov.preimages.slice(0, n).map((p) => Buffer.from(p))
		};
	}

	/**
	 * Breach watch (spec §9.4): decide whether a transaction spending the
	 * channel funding outpoint is the revoked C_{n0}^S, and — option (a),
	 * when R provisioned the scoped revocation secret + mandated sweep
	 * script — build the fully-witnessed justice transaction sweeping S's
	 * revocable outputs. R's own to_remote output is untouched: the tower
	 * holds no payment key (scoped-key boundary) and that output is not
	 * time-critical (only R can ever claim it).
	 *
	 * The chain feed itself is transport (out of scope): callers watch the
	 * funding outpoint and hand any spend here.
	 */
	checkBroadcast(
		tx: bitcoin.Transaction,
		blockHeight: number
	): IFforTowerBreachResult {
		const none: IFforTowerBreachResult = { breach: false, justiceTxs: [] };
		if (!this._prov || !this._record) return none;
		// Only spends of OUR funding outpoint are of interest.
		const c = this._prov.channel;
		const spendsFunding = tx.ins.some(
			(i) =>
				Buffer.from(i.hash).equals(c.fundingTxid) &&
				i.index === c.fundingOutputIndex
		);
		if (!spendsFunding) return none;
		// Before package 1 the tower holds no revocation secret: C_{n0}^S is
		// still S's legitimate state (§9.3) — nothing to do.
		if (!this._record.revocationSecretN0Hex) return none;

		const state = this._buildMirrorState();
		state.shaChainStore.addSecret(
			MAX_INDEX - c.n0,
			Buffer.from(this._record.revocationSecretN0Hex, 'hex')
		);
		const classified = classifyCommitmentTx(tx, state);
		if (classified.type !== CommitmentType.THEIR_REVOKED_COMMITMENT) {
			return none;
		}

		const alert = `revoked commitment ${tx.getId()} (index ${
			classified.commitmentNumber
		}) broadcast by S`;
		if (!this._prov.revocationBasepointSecret || !this._prov.sweepScript) {
			// Option (b): alert-only tower.
			return { breach: true, alert, justiceTxs: [] };
		}

		// Option (a): build the justice tx with the scoped revocation key.
		const tracked = classifyOutputs(
			tx,
			state,
			CommitmentType.THEIR_REVOKED_COMMITMENT,
			classified.commitmentNumber
		).filter((o) => o.outputType !== OutputType.TO_REMOTE);
		for (const o of tracked) {
			o.confirmationHeight = blockHeight;
		}
		const resolved = resolveRevokedCommitmentOutputs(
			state,
			tracked,
			classified.commitmentNumber,
			tx,
			this._prov.sweepScript,
			10,
			this._prov.revocationBasepointSecret,
			// Payment key intentionally NOT provisioned (scoped-key boundary);
			// TO_REMOTE outputs were filtered out above so this is never used.
			Buffer.alloc(32, 1),
			this._prov.network ?? bitcoin.networks.bitcoin
		);
		const justiceTxs: Buffer[] = [];
		for (const r of resolved) {
			if (r.spendTx) {
				if (r.witness) r.spendTx.setWitness(0, r.witness);
				justiceTxs.push(r.spendTx.toBuffer());
			}
		}
		return { breach: true, alert, justiceTxs };
	}

	// ─────────────── Internals ───────────────

	/**
	 * Signature verification helper: ChannelSigner requires a private key but
	 * the tower's checklist only ever calls its verify methods (pubkey-based).
	 * The throwaway key never signs anything.
	 */
	private _verifyOnlySigner(): ChannelSigner {
		return new ChannelSigner(Buffer.alloc(32, 1), Buffer.alloc(32, 1));
	}

	/**
	 * Synthesize R's mirror of the channel state from the provisioned statics
	 * (exactly the state R itself would validate packages against). The tower
	 * has no per-commitment seed — every point it needs was pre-shared, and
	 * the checklist passes points explicitly.
	 */
	private _buildMirrorState(): IChannelState {
		const c = this._prov!.channel;
		const base = c.rIsOpener
			? createOpenerState({
					temporaryChannelId: Buffer.alloc(32),
					fundingSatoshis: c.fundingSatoshis,
					pushMsat: 0n,
					localConfig: { ...c.rConfig },
					localBasepoints: c.rBasepoints,
					localPerCommitmentSeed: Buffer.alloc(32) // never used: points are pre-shared
			  })
			: createAcceptorState({
					temporaryChannelId: Buffer.alloc(32),
					fundingSatoshis: c.fundingSatoshis,
					pushMsat: 0n,
					localConfig: { ...c.rConfig },
					localBasepoints: c.rBasepoints,
					localPerCommitmentSeed: Buffer.alloc(32),
					remoteBasepoints: c.sBasepoints,
					remoteConfig: { ...c.sConfig }
			  });
		base.remoteBasepoints = c.sBasepoints;
		base.remoteConfig = { ...c.sConfig };
		base.fundingTxid = c.fundingTxid;
		base.fundingOutputIndex = c.fundingOutputIndex;
		base.channelType = Buffer.from(c.channelType);
		base.state = ChannelState.NORMAL;
		base.localCommitmentNumber = c.nR;
		base.remoteCommitmentNumber = c.n0;
		base.localBalanceMsat = c.preEpochRLocalMsat;
		base.remoteBalanceMsat = c.preEpochSLocalMsat;
		base.remoteCurrentPerCommitmentPoint = Buffer.from(c.sPerCommitmentPointN0);
		return base;
	}

	/** The tower's persistent epoch view (mirrors R's IFforEpochStateData). */
	private _buildEpochView(): IFforEpochStateData {
		const p = this._prov!;
		return {
			epochId: Buffer.from(p.epochId),
			role: 'recipient',
			state: FforEpochState.FF_EPOCH,
			params: p.params,
			sCommitmentNumber: p.channel.n0,
			invoices: [],
			escapeSigs: [],
			escapeHtlcSigs: [],
			initSignature: null,
			acceptSignature: null,
			remoteNodeId: Buffer.from(p.sNodeId),
			epochStartHeight: null,
			preimages: [],
			lastSeq: this._record?.lastReleased ?? 0,
			packages: [],
			htlcAmountsMsat: [],
			voucherAmountsMsat: [],
			upstreamFulfilled: [],
			sHtlcIdBase: 0n,
			frozenFeeratePerKw: p.channel.frozenFeeratePerKw,
			nR: p.channel.nR,
			rPreEpochPoint: null,
			peerLastSeq: null
		};
	}
}

// ─────────────── Client interface + in-process loopback ───────────────

/**
 * How S and R reach the tower. The spec leaves transport out of scope
 * (HTTPS, onion message, or a direct Noise connection all work); tests use
 * the in-process loopback, and example/ffor-tower.ts serves the same tower
 * over a trivial TCP JSON-lines transport.
 */
export interface IFforTowerClient {
	provision(p: IFforTowerProvisioning): Promise<void>;
	requestRelease(pkg: Buffer): Promise<IFforTowerReleaseResult>;
	fetch(req: IFforTowerFetchRequest): Promise<IFforTowerFetchResponse>;
}

export class LoopbackTowerClient implements IFforTowerClient {
	constructor(private tower: FforTower) {}

	async provision(p: IFforTowerProvisioning): Promise<void> {
		this.tower.provision(p);
	}

	async requestRelease(pkg: Buffer): Promise<IFforTowerReleaseResult> {
		return this.tower.handleReleaseRequest(pkg);
	}

	async fetch(req: IFforTowerFetchRequest): Promise<IFforTowerFetchResponse> {
		return this.tower.handleFetch(req);
	}
}

/** Convenience for provisioning: R-generated preimages handed to T (§9.4). */
export function generateTowerPreimages(k: number): {
	preimages: Buffer[];
	paymentHashes: Buffer[];
} {
	const preimages = Array.from({ length: k }, () => crypto.randomBytes(32));
	return {
		preimages,
		paymentHashes: preimages.map((p) =>
			crypto.createHash('sha256').update(p).digest()
		)
	};
}

/** A tower's "node id" for ff_init TLV 3 when it has its own identity key. */
export function towerNodeIdFromKey(privateKey: Buffer): Buffer {
	return getPublicKey(privateKey);
}
