/**
 * FFOR: Fast-Forward Offline Receive (specs/ffor-offline-receive.md) — types.
 *
 * M1 scope: epoch establishment (spec §7) — parameter/state types shared by the
 * wire codecs (./messages.ts), the epoch state machine (./epoch.ts), and
 * channel-state persistence. Settlement packages, reconciliation, towers, and
 * escape-commitment construction are M2+.
 */

/** Spec §3: roles. `R` goes offline and is credited; `S` settles upstream. */
export type FforRole = 'recipient' | 'settlement_peer';

/** Spec §7.1 `variant`: 1 = A (self-contained), 2 = B (tower-mediated). */
export enum FforVariant {
	A = 1,
	B = 2
}

/**
 * Epoch lifecycle states (spec §6/§15: SETUP → EPOCH → RECONCILE → CLOSED).
 * The FF_SETUP_* sub-states track handshake progress; roles are recorded
 * separately, so a state names the same point in the handshake on both sides
 * (e.g. FF_SETUP_INIT = ff_init sent (R) / received-and-accepted (S)).
 */
export enum FforEpochState {
	/** ff_init sent (R) / valid ff_init received (S). */
	FF_SETUP_INIT = 'FF_SETUP_INIT',
	/** ff_accept sent (S) — R jumps straight from FF_SETUP_INIT to FF_EPOCH
	 *  because it emits ff_invoices/ff_escape_sigs/ff_begin in one batch. */
	FF_SETUP_ACCEPTED = 'FF_SETUP_ACCEPTED',
	/** ff_invoices received (S). */
	FF_SETUP_INVOICES = 'FF_SETUP_INVOICES',
	/** ff_escape_sigs received (S, only when G > 0). */
	FF_SETUP_ESCAPE_SIGS = 'FF_SETUP_ESCAPE_SIGS',
	/** Epoch active: only fast-forward settlement / reestablish / ff_end legal. */
	FF_EPOCH = 'FF_EPOCH',
	/** Reconciliation (spec §11) — placeholder, implemented in M2. */
	FF_RECONCILE = 'FF_RECONCILE',
	/** Epoch closed (cooperatively via ff_end, or aborted pre-ff_begin). */
	FF_CLOSED = 'FF_CLOSED'
}

/**
 * Epoch parameters, mirroring the ff_init field table (spec §7.1).
 * All heights are absolute block heights; all amounts are millisatoshis.
 */
export interface IFforEpochParams {
	/** 1 = Variant A (S generates hashes), 2 = Variant B (tower generates). */
	variant: FforVariant;
	/** Max cumulative voucher value this epoch (msat). */
	budgetMsat: bigint;
	/** `K`: max number of delegated payments (≤ open HTLC slot budget, §8). */
	maxPayments: number;
	/** Below this, S MUST reject/fall back (≥ voucher dust floor, §8). */
	minPaymentMsat: bigint;
	/** `D`: absolute height; no new delegated settlements after. */
	settlementDeadline: number;
	/** `T_exp`: absolute height; vouchers/escapes revert to S after.
	 *  MUST satisfy T_exp ≥ D + FFOR_RECONCILE_MARGIN_BLOCKS. */
	voucherExpiry: number;
	/** S's per-payment skim, base (msat). */
	feeBaseMsat: number;
	/** S's per-payment skim, proportional (millionths). */
	feeProportionalMillionths: number;
	/** `G`: 0 = no escape; else escape step size in msat (§10). */
	escapeGranularityMsat: bigint;
	/**
	 * R's per-commitment points for commitment numbers n_R+1 … n_R+K,
	 * pre-shared so S can build C_i^R alone (§7.1). Exactly K entries.
	 */
	rPerCommitmentPoints: Buffer[];
	/**
	 * The epoch's payment hash set H_1…H_K. Variant B: supplied by R's tower and
	 * carried in ff_init TLV 1. Variant A: generated by S and carried in
	 * ff_accept TLV 1 (adopted into params when the accept is processed).
	 */
	paymentHashes?: Buffer[];
	/** Variant B only (ff_init TLV 3): tower node id, 33 bytes. */
	towerNodeId?: Buffer;
	/** Variant B only (ff_init TLV 5): how S reaches the tower. */
	towerUri?: string;
}

/**
 * Full persisted epoch state: everything both sides MUST durably store before
 * ff_begin (spec §7.5), plus the signed-message evidence retained for the
 * fraud-proof inventory (§12.2).
 */
export interface IFforEpochStateData {
	/** 32-byte epoch id (generated by R; unique per channel). */
	epochId: Buffer;
	role: FforRole;
	state: FforEpochState;
	params: IFforEpochParams;
	/** `n0`: S's commitment number at epoch start (from ff_accept). */
	sCommitmentNumber: bigint | null;
	/** The K pre-signed amountless BOLT 11 invoice strings (spec §7.3). */
	invoices: string[];
	/** R's signatures on escape commitments E_1…E_J (§7.4; zero placeholders
	 *  in M1 — escape construction/signing lands in M3/M5). */
	escapeSigs: Buffer[];
	/** Reserved aggregate-voucher spend-path sigs (§7.4; unused in v1). */
	escapeHtlcSigs: Buffer[];
	/** R's node-key signature over ff_init (non-repudiation evidence, §12.2). */
	initSignature: Buffer | null;
	/** S's node-key signature over ff_accept (evidence, §12.2). */
	acceptSignature: Buffer | null;
	/** The peer node id the signed messages verify against (evidence context). */
	remoteNodeId: Buffer | null;
	/** From ff_begin (§7.5), for audit. */
	epochStartHeight: number | null;

	// ── M2: settlement + reconciliation state (spec §9/§11) ──

	/**
	 * Payment preimages P_1…P_K, indexed by seq−1 (zero-length = unknown).
	 * Variant A: generated by S at ff_accept (P_1 = per_commitment_secret_S[n0],
	 * §7.2/§12.1) and retained durably; on R the array fills as packages are
	 * validated during replay.
	 */
	preimages: Buffer[];
	/** Number of settled (S) / validated (R) settlement packages. */
	lastSeq: number;
	/**
	 * Raw encoded ff_settlement payloads, indexed by seq−1. S persists each
	 * BEFORE settling upstream (§9.2) and replays them at reconciliation;
	 * R stores the received copies as signed evidence (§12.2).
	 */
	packages: Buffer[];
	/** htlc_amount_msat per settlement (seq−1 indexed; audit + rebuild). */
	htlcAmountsMsat: bigint[];
	/** v_k = htlc_amount − fee(htlc_amount) per settlement (seq−1 indexed). */
	voucherAmountsMsat: bigint[];
	/**
	 * S side: whether the upstream HTLC for seq k was already fulfilled
	 * (seq−1 indexed). Persisted after the fulfill goes out, so a crash between
	 * package-persist and upstream-settle replays idempotently (§9.2), while a
	 * later duplicate-hash part is failed (§11.2).
	 */
	upstreamFulfilled: boolean[];
	/**
	 * Base HTLC id for voucher HTLCs at reconciliation: voucher seq k becomes
	 * HTLC id sHtlcIdBase + (k−1). This is S's offered-HTLC counter at epoch
	 * start; the spec does not assign voucher HTLC ids, so the prototype
	 * carries it in ff_accept TLV 7 (odd, prototype extension — spec erratum).
	 */
	sHtlcIdBase: bigint;
	/** The commitment feerate frozen for the epoch (spec §5), snapshotted at setup. */
	frozenFeeratePerKw: number;
	/** n_R: R's commitment number at epoch start (C_i^R = n_R + i). */
	nR: bigint;
	/**
	 * S side: R's CURRENT per-commitment point at epoch start (commitment n_R).
	 * Snapshotted because reconciliation overwrites the live tracking fields
	 * before ff_revoke_batch verifies the n_R secret against it.
	 */
	rPreEpochPoint: Buffer | null;
	/**
	 * The peer's last_seq from its reestablish TLV (spec §11.1): R learns j
	 * (how many packages to expect in replay) from S's value.
	 */
	peerLastSeq: number | null;
	/**
	 * S side: per_commitment_secret_S[n0], the seq-1 pre-revocation (§9.1 TLV 1,
	 * REQUIRED both variants). Variant A: this also equals P_1 (§7.2 binding) so
	 * it doubles as preimages[0]. Variant B: the tower's P_1 is unrelated, so S
	 * keeps its own n0 secret here. Undefined on R (R never signs packages).
	 */
	sRevocationSecretN0?: Buffer;
	/**
	 * Escapes (§10, Appendix B): the FROZEN pre-epoch state the escape set E_j
	 * was built and signed against. Live channel balances/points move after
	 * reconciliation, so these must be snapshotted at setup to rebuild/recognize
	 * an escape later (S broadcast, R claim, stale-escape penalty). Only set
	 * when G > 0.
	 */
	preEpochSLocalMsat?: bigint;
	preEpochRLocalMsat?: bigint;
	/** S's per-commitment point at n0+1 (where escapes live). */
	sPointN0Plus1?: Buffer;
	/** Whether S is the channel opener/funder (escape fee side). */
	sIsOpener?: boolean;
	/** S's to_self_delay on its to_local (R's requirement). */
	sToSelfDelay?: number;
}

/**
 * Spec §7.1: recommended reconciliation margin — ff_init MUST satisfy
 * `T_exp ≥ D + reconcile_margin` (recommended margin ≥ 1008 blocks ≈ 1 week).
 * M1 enforces the recommended value.
 */
export const FFOR_RECONCILE_MARGIN_BLOCKS = 1008;

/**
 * Spec §7.5: ff_begin's epoch_start_height "MUST be within a few blocks of
 * current tip". Enforced only when the receiver knows the current height.
 */
export const FFOR_BEGIN_MAX_HEIGHT_SKEW = 6;

/**
 * Spec §8: S accepts a delegated payment only while
 * `height < upstream cltv_expiry − safety delta`. The delta mirrors the
 * default min_final_cltv_expiry headroom.
 */
export const FFOR_SETTLEMENT_SAFETY_DELTA = 40;

/**
 * Spec §10: S MAY broadcast an escape only when
 * `current height > D + escape_delay` (recommended escape_delay ≥ 2016).
 */
export const FFOR_ESCAPE_DELAY_BLOCKS = 2016;

/**
 * Everything the epoch state machine needs to know about the channel (and the
 * caller's key material) to validate and drive the setup handshake. Built by
 * Channel per message; keeps ./epoch.ts free of a dependency on the Channel
 * class itself.
 */
export interface IFforChannelContext {
	channelId: Buffer;
	/** Current chain tip height; 0 = unknown (height checks are skipped). */
	currentBlockHeight: number;
	/** Negotiated channel type is anchors (spec §5 prerequisite). */
	isAnchor: boolean;
	/** Our balance (msat) — S's spendable side when we are S. */
	localBalanceMsat: bigint;
	remoteBalanceMsat: bigint;
	localDustLimitSat: bigint;
	remoteDustLimitSat: bigint;
	localMaxAcceptedHtlcs: number;
	remoteMaxAcceptedHtlcs: number;
	/** Reserve WE must maintain (peer-required), satoshis. */
	localRequiredReserveSat: bigint;
	/** Reserve the PEER must maintain (we required it), satoshis. */
	remoteRequiredReserveSat: bigint;
	/** The frozen commitment feerate for the epoch (spec §5). */
	feeratePerKw: number;
	/** Our current commitment number (S reports this as n0 in ff_accept). */
	localCommitmentNumber: bigint;
	/** The PEER's current commitment number (S snapshots this as n_R). */
	remoteCommitmentNumber: bigint;
	/** The peer's current per-commitment point (S snapshots R's n_R point). */
	remoteCurrentPerCommitmentPoint?: Buffer | null;
	/** Epoch ids already used on this channel (uniqueness check). */
	usedEpochIds: Set<string>;
	/** Peer node id — verifies the ✍ messages' node-key signatures. */
	remoteNodeId?: Buffer;
	/** Signs a 32-byte digest with OUR node key (64-byte compact sig). */
	signFn?: (digest: Buffer) => Buffer;
	/**
	 * R side: builds the K amountless BOLT 11 invoice strings for the epoch's
	 * payment hashes (spec §7.3). Must return exactly hashes.length strings.
	 */
	invoiceFactory?: (paymentHashes: Buffer[]) => string[];
	/**
	 * S side (variant A, §7.2): our per-commitment SECRET at n0, so ff_accept
	 * can bind H_1 = SHA256(per_commitment_secret_S[n0]).
	 */
	localPerCommitmentSecretN0?: Buffer;
	/** S side: our offered-HTLC counter at epoch start (voucher id base). */
	localNextHtlcId?: bigint;
	/**
	 * R side (§7.4/§10, Appendix B): build R's J funding-key signatures over the
	 * deterministic escape set E_1..E_J for these params. Returns J compact
	 * 64-byte sigs. Provided by the Channel (only it holds the statics). Absent
	 * ⇒ escapes cannot be signed (epoch refused when G > 0).
	 */
	buildEscapeSigs?: (params: IFforEpochParams) => Buffer[];
	/**
	 * S side: verify R's escape signature set against the deterministic escape
	 * commitments (Appendix B.1). Returns null when all verify, else a rejection
	 * reason; S MUST refuse the epoch on any failure.
	 */
	verifyEscapeSigs?: (
		params: IFforEpochParams,
		sigs: Buffer[]
	) => string | null;
}

/** One encoded message for the peer, in send order. */
export interface IFforSend {
	type: number;
	payload: Buffer;
}

/** Result of driving the epoch state machine with one call/message. */
export interface IFforHandleResult {
	ok: boolean;
	/** Human-readable reason when !ok (also carried in any ff_error send). */
	error?: string;
	/** Encoded messages to send to the peer, in order. */
	sends: IFforSend[];
	/** The epoch just became active — channel must enter ChannelState.FF_EPOCH. */
	enteredEpoch?: boolean;
	/** The epoch closed cooperatively — channel returns to NORMAL. */
	closed?: boolean;
	/** Setup aborted (clean, pre-ff_begin §11.1) — discard epoch, back to NORMAL. */
	aborted?: boolean;
	/**
	 * Spec §7.5: persist the full epoch state durably BEFORE the sends go out
	 * (set when the sends include ff_begin / when entering FF_EPOCH).
	 */
	persistFirst?: boolean;
}
