/**
 * FFOR: Fast-Forward Offline Receive (specs/ffor-offline-receive.md) — types.
 *
 * M1 scope: epoch establishment (spec §7) — parameter/state types shared by the
 * wire codecs (./messages.ts), the epoch state machine (./epoch.ts), and
 * channel-state persistence. Settlement packages, reconciliation, towers, and
 * escape-commitment construction are M2+.
 */

/** Spec §3: roles. `R` goes offline and is credited; `S` settles upstream. */
export type FforRole = 'recipient' | 'settlement_peer';

/** Spec §7.1 `variant`: 1 = A (self-contained), 2 = B (tower-mediated). */
export enum FforVariant {
	A = 1,
	B = 2
}

/**
 * Epoch lifecycle states (spec §6/§15: SETUP → EPOCH → RECONCILE → CLOSED).
 * The FF_SETUP_* sub-states track handshake progress; roles are recorded
 * separately, so a state names the same point in the handshake on both sides
 * (e.g. FF_SETUP_INIT = ff_init sent (R) / received-and-accepted (S)).
 */
export enum FforEpochState {
	/** ff_init sent (R) / valid ff_init received (S). */
	FF_SETUP_INIT = 'FF_SETUP_INIT',
	/** ff_accept sent (S) — R jumps straight from FF_SETUP_INIT to FF_EPOCH
	 *  because it emits ff_invoices/ff_escape_sigs/ff_begin in one batch. */
	FF_SETUP_ACCEPTED = 'FF_SETUP_ACCEPTED',
	/** ff_invoices received (S). */
	FF_SETUP_INVOICES = 'FF_SETUP_INVOICES',
	/** ff_escape_sigs received (S, only when G > 0). */
	FF_SETUP_ESCAPE_SIGS = 'FF_SETUP_ESCAPE_SIGS',
	/** Epoch active: only fast-forward settlement / reestablish / ff_end legal. */
	FF_EPOCH = 'FF_EPOCH',
	/** Reconciliation (spec §11) — placeholder, implemented in M2. */
	FF_RECONCILE = 'FF_RECONCILE',
	/** Epoch closed (cooperatively via ff_end, or aborted pre-ff_begin). */
	FF_CLOSED = 'FF_CLOSED'
}

/**
 * Epoch parameters, mirroring the ff_init field table (spec §7.1).
 * All heights are absolute block heights; all amounts are millisatoshis.
 */
export interface IFforEpochParams {
	/** 1 = Variant A (S generates hashes), 2 = Variant B (tower generates). */
	variant: FforVariant;
	/** Max cumulative voucher value this epoch (msat). */
	budgetMsat: bigint;
	/** `K`: max number of delegated payments (≤ open HTLC slot budget, §8). */
	maxPayments: number;
	/** Below this, S MUST reject/fall back (≥ voucher dust floor, §8). */
	minPaymentMsat: bigint;
	/** `D`: absolute height; no new delegated settlements after. */
	settlementDeadline: number;
	/** `T_exp`: absolute height; vouchers/escapes revert to S after.
	 *  MUST satisfy T_exp ≥ D + FFOR_RECONCILE_MARGIN_BLOCKS. */
	voucherExpiry: number;
	/** S's per-payment skim, base (msat). */
	feeBaseMsat: number;
	/** S's per-payment skim, proportional (millionths). */
	feeProportionalMillionths: number;
	/** `G`: 0 = no escape; else escape step size in msat (§10). */
	escapeGranularityMsat: bigint;
	/**
	 * R's per-commitment points for commitment numbers n_R+1 … n_R+K,
	 * pre-shared so S can build C_i^R alone (§7.1). Exactly K entries.
	 */
	rPerCommitmentPoints: Buffer[];
	/**
	 * The epoch's payment hash set H_1…H_K. Variant B: supplied by R's tower and
	 * carried in ff_init TLV 1. Variant A: generated by S and carried in
	 * ff_accept TLV 1 (adopted into params when the accept is processed).
	 */
	paymentHashes?: Buffer[];
	/** Variant B only (ff_init TLV 3): tower node id, 33 bytes. */
	towerNodeId?: Buffer;
	/** Variant B only (ff_init TLV 5): how S reaches the tower. */
	towerUri?: string;
}

/**
 * Full persisted epoch state: everything both sides MUST durably store before
 * ff_begin (spec §7.5), plus the signed-message evidence retained for the
 * fraud-proof inventory (§12.2).
 */
export interface IFforEpochStateData {
	/** 32-byte epoch id (generated by R; unique per channel). */
	epochId: Buffer;
	role: FforRole;
	state: FforEpochState;
	params: IFforEpochParams;
	/** `n0`: S's commitment number at epoch start (from ff_accept). */
	sCommitmentNumber: bigint | null;
	/** The K pre-signed amountless BOLT 11 invoice strings (spec §7.3). */
	invoices: string[];
	/** R's signatures on escape commitments E_1…E_J (§7.4; zero placeholders
	 *  in M1 — escape construction/signing lands in M3/M5). */
	escapeSigs: Buffer[];
	/** Reserved aggregate-voucher spend-path sigs (§7.4; unused in v1). */
	escapeHtlcSigs: Buffer[];
	/** R's node-key signature over ff_init (non-repudiation evidence, §12.2). */
	initSignature: Buffer | null;
	/** S's node-key signature over ff_accept (evidence, §12.2). */
	acceptSignature: Buffer | null;
	/** The peer node id the signed messages verify against (evidence context). */
	remoteNodeId: Buffer | null;
	/** From ff_begin (§7.5), for audit. */
	epochStartHeight: number | null;
}

/**
 * Spec §7.1: recommended reconciliation margin — ff_init MUST satisfy
 * `T_exp ≥ D + reconcile_margin` (recommended margin ≥ 1008 blocks ≈ 1 week).
 * M1 enforces the recommended value.
 */
export const FFOR_RECONCILE_MARGIN_BLOCKS = 1008;

/**
 * Spec §7.5: ff_begin's epoch_start_height "MUST be within a few blocks of
 * current tip". Enforced only when the receiver knows the current height.
 */
export const FFOR_BEGIN_MAX_HEIGHT_SKEW = 6;

/**
 * Everything the epoch state machine needs to know about the channel (and the
 * caller's key material) to validate and drive the setup handshake. Built by
 * Channel per message; keeps ./epoch.ts free of a dependency on the Channel
 * class itself.
 */
export interface IFforChannelContext {
	channelId: Buffer;
	/** Current chain tip height; 0 = unknown (height checks are skipped). */
	currentBlockHeight: number;
	/** Negotiated channel type is anchors (spec §5 prerequisite). */
	isAnchor: boolean;
	/** Our balance (msat) — S's spendable side when we are S. */
	localBalanceMsat: bigint;
	remoteBalanceMsat: bigint;
	localDustLimitSat: bigint;
	remoteDustLimitSat: bigint;
	localMaxAcceptedHtlcs: number;
	remoteMaxAcceptedHtlcs: number;
	/** Reserve WE must maintain (peer-required), satoshis. */
	localRequiredReserveSat: bigint;
	/** Reserve the PEER must maintain (we required it), satoshis. */
	remoteRequiredReserveSat: bigint;
	/** The frozen commitment feerate for the epoch (spec §5). */
	feeratePerKw: number;
	/** Our current commitment number (S reports this as n0 in ff_accept). */
	localCommitmentNumber: bigint;
	/** Epoch ids already used on this channel (uniqueness check). */
	usedEpochIds: Set<string>;
	/** Peer node id — verifies the ✍ messages' node-key signatures. */
	remoteNodeId?: Buffer;
	/** Signs a 32-byte digest with OUR node key (64-byte compact sig). */
	signFn?: (digest: Buffer) => Buffer;
	/**
	 * R side: builds the K amountless BOLT 11 invoice strings for the epoch's
	 * payment hashes (spec §7.3). Must return exactly hashes.length strings.
	 */
	invoiceFactory?: (paymentHashes: Buffer[]) => string[];
}

/** One encoded message for the peer, in send order. */
export interface IFforSend {
	type: number;
	payload: Buffer;
}

/** Result of driving the epoch state machine with one call/message. */
export interface IFforHandleResult {
	ok: boolean;
	/** Human-readable reason when !ok (also carried in any ff_error send). */
	error?: string;
	/** Encoded messages to send to the peer, in order. */
	sends: IFforSend[];
	/** The epoch just became active — channel must enter ChannelState.FF_EPOCH. */
	enteredEpoch?: boolean;
	/** The epoch closed cooperatively — channel returns to NORMAL. */
	closed?: boolean;
	/** Setup aborted (clean, pre-ff_begin §11.1) — discard epoch, back to NORMAL. */
	aborted?: boolean;
	/**
	 * Spec §7.5: persist the full epoch state durably BEFORE the sends go out
	 * (set when the sends include ff_begin / when entering FF_EPOCH).
	 */
	persistFirst?: boolean;
}
